### PR TITLE
Patch Bokeh Django server consumers to load resources

### PR DESCRIPTION
**Pull request by philippjfr**
@Hoxbro Could you test this? If you want I'll cut a new RC release.

### CODE REVIEW

**Comment by Hoxbro** [comment]
The first problem mentioned in https://discourse.holoviz.org/t/panel-0-11-0-rc3/1898/4 is fixed with this.

The second problem seem to be fixed by updating holoviews to the latest version.

The third problem is still happening.

**Comment by philippjfr** [comment]
Hmm, can you share that dashboard code somehow?

**Comment by Hoxbro** [comment]
Unfortunately i cannot share it.  I will try to make a minimal working example later today.

**Comment by Hoxbro** [comment]
I have minimal working example [here](https://github.com/holoviz/panel/files/6050867/django_crash.zip).

It only seem to crash under certain conditions, so I hope you are able to recreate it. I have attached a video of it happening below. 

https://user-images.githubusercontent.com/19758978/109324521-0ff1f300-7855-11eb-8faf-d2b9eef05b65.mp4

**Comment by philippjfr** [comment]
So sadly I can't reproduce any issue with that example. What OS are you running this on?

**Comment by Hoxbro** [comment]
My OS is Windows. I tried to create a clean environment where it still happens, my fresh environment is below. The weird part is it work fine when I'm debugging in vs code, but crashes when I'm running from command line.  

If you can't recreate it, it is probably something wrong with the set-up on my computer, but what I simply don't know. 


``` yaml
name: django_crash
channels:
  - pyviz/label/dev
  - bokeh
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.3.1
  - attrs=20.3.0
  - autobahn=21.2.1
  - automat=20.2.0
  - bcrypt=3.2.0
  - blas=1.0
  - bokeh=2.3.0
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - channels=2.4.0
  - chardet=4.0.0
  - constantly=15.1.0
  - cryptography=3.4.4
  - daphne=2.5.0
  - django=3.0.9
  - freetype=2.10.4
  - hyperlink=21.0.0
  - icc_rt=2019.0.0
  - idna=2.10
  - importlib-metadata=3.7.0
  - incremental=17.5.0
  - intel-openmp=2020.3
  - jinja2=2.11.3
  - jpeg=9d
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - markdown=3.3.3
  - markupsafe=1.1.1
  - mkl=2020.4
  - mkl-service=2.3.0
  - numpy=1.20.1
  - olefile=0.46
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.2
  - panel=0.11.0rc4
  - param=1.10.1
  - pillow=8.1.0
  - pip=21.0.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyct=0.4.8
  - pyct-core=0.4.8
  - pyhamcrest=2.0.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyviz_comms=2.0.1
  - pywin32=300
  - pyyaml=5.4.1
  - requests=2.25.1
  - scipy=1.6.1
  - service_identity=18.1.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.34.0
  - sqlparse=0.4.1
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.58.0
  - twisted=20.3.0
  - txaio=21.2.1
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zope.interface=5.2.0
  - zstd=1.4.8
```

**Comment by Hoxbro** [comment]
An update: Tried the problem in [Windows Sandbox](https://techcommunity.microsoft.com/t5/windows-kernel-internals/windows-sandbox/ba-p/301849) (a built-in virtual machine). 
The problem still occur, but it also occur for a multitude of combinations of previous version of panel/bokeh/django. 
So this problem/bug should in my opinion not be a release blocker (if it ever was).

**Comment by philippjfr** [comment]
Thank you, really appreciate you investigating. Could you open an issue so we can investigate later?

**Pull request merged**
