### PR TITLE
End align widgets in Param Row layout

### PR DESCRIPTION
**Pull request by xavArtley**
fix: #1375

### CODE REVIEW

**Comment by xavArtley** [comment]
was wondering if we should not align all widgets to the end in a Row layout
image

**Comment by philippjfr** [comment]
>was wondering if we should not align all widgets to the end in a Row layout

That's a good question and it seems like a good idea to me.

**Comment by MarcSkovMadsen** [comment]
There is a similar problem as far as i remember if the default layout is a gridspec or gridbox.

**Comment by xavArtley** [comment]
May be the default align of widgets should be 'end' no matter the layout?

**Comment by philippjfr** [comment]
>May be the default align of widgets should be 'end' no matter the layout?

Could you add a commit to the `Widget` baseclass with, defining

```python
    align = param.ObjectSelector(default='end',
                                 objects=['start', 'end', 'center'], doc="""
        Whether the object should be aligned with the start, end or
        center of its container""")
```

and then append `[doc-build]` to the commit message? Then we can see what that would look like.

**Comment by xavArtley** [comment]
Setting widgets align to end by default:
image

**Comment by xavArtley** [comment]
The main issue of align is it aligns both horizontal and vertically the widget layout:

image

**Comment by xavArtley** [comment]
To make a widget bottom left align we must define a custom class and some raw css:
image

**Comment by MarcSkovMadsen** [comment]
You’re so cool. 

Thought this was just one of the friction points I would have to live with 👍

**Comment by philippjfr** [comment]
>The main issue of align is it aligns both horizontally and vertically the widget layout:

Hmm, that's a good point, the CSS solution seems okay but possibly isn't ideal. Will have to think about it a bit.

**Comment by philippjfr** [comment]
Closing for now in favor of https://github.com/holoviz/panel/pull/1504. May have to fall back to the CSS solution for grids though.

**Pull request closed without merging**
