### PR TITLE
Various docs updates

### PR DESCRIPTION
**Pull request by maximlt**
- [x] Move "Apply Templates" to the *Build apps* section
- [x] Update the how-to template screenshots
- [x] Update the reference template screenshots (Golden missing)
- [x] Update the template references (not yet settled on the API to use in the examples)
- [x] Add the JupyterLab Preview How-To guide
- [x] Review API usage (pn.bind, pn.state.served, etc.)
- [ ] Add the load balancing How-To guide
- [x] Add the Param explanation

### CODE REVIEW

**Comment by maximlt** [comment]
@philippjfr I have not updated the GoldenTemplate screenshots as I think that template will need some additional tweaking. Here's how it looks currently with the dark theme:

image

I have added a Param explanation.

**Comment by philippjfr** [comment]
Have you rebundled with `panel bundle --themes --templates`?

**Comment by maximlt** [comment]
Ha that seems to work now, I'll update the screenshots immediately. I've been running `panel bundle --all` regularly, not at the right time I guess.

**Comment by philippjfr** [comment]
Ready to review/merge? Don't expect you to write the load balancing guide.

**Comment by philippjfr** [comment]
Ready to review/merge? Don't expect you to write the load balancing guide.

**Comment by maximlt** [comment]
Yes ready for review!

**Comment by philippjfr** [comment]
Really great effort. Will merge.

**Pull request merged**
