### PR TITLE
Fixes https://github.com/holoviz/panel/issues/2165

### PR DESCRIPTION
**Pull request by hyamanieu**

### CODE REVIEW

**Comment by hyamanieu** [comment]
#2165

**Comment by philippjfr** [comment]
Great, thank you!

**Comment by philippjfr** [comment]
Error on the py3.7 build is transient, will merge shortly.

**Comment by philippjfr** [comment]
Bunch of weird transients here but no real issues.

**Comment by hyamanieu** [comment]
> Great, thank you!

gotta get that v0.12.0 rolling!

> Bunch of weird transients here but no real issues.

I have seen also a problem with plotly not installing on the windows test in another PR, although it had nothing to do with it.

**Comment by philippjfr** [comment]
Yep, final sprint for 0.12.0. Will tag 0.12.0rc1 later today and give the CI setup some love, definitely some issues with Windows+Plotly.

**Pull request merged**
