### PR TITLE
SpeechToText Widget

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Preliminary SpeechToTextWidget.

I've implemented, test and created parts of a Notebook. The functionality seems to be there.

But I need to learn and improve from some more advanced examples. And finalize the notebook.

The PR is showcased here https://discourse.holoviz.org/t/happy-new-year-w-speechtotext-widget-pr/1637. This includes a video of it.

FYI. @philippjfr

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
The Reference Notebook is now ready for review. I identified some bugs and fixed them while developing.

**Comment by MarcSkovMadsen** [comment]
FYI. @philippjfr 

I have finalized the implementation and testing. I don't plan to do anything more on this before I get feedback from review or users.

**Comment by MarcSkovMadsen** [comment]
The gallery notebook is "demoed" here https://discourse.holoviz.org/t/texttospeech-example-pr/1646

**Comment by philippjfr** [comment]
Three comments:

1) Needs to be rebased
2) Indentation in .ts files should be 2 spaces
3) A few flake errors (just add `# noqa`)

**Comment by MarcSkovMadsen** [comment]
Regarding the 3 flake "line too long errors" they do not make sense. As you can see below the line is NOT too long. Thus there is nothing I can fix. @philippjfr 

image

**Comment by MarcSkovMadsen** [comment]
I've fixed what I can fix (see flake comment above).

I have run `panel build panel` and use bokeh==2.3.0.dev12 but now I get an error when I run `python -m panel serve 'panel\tests\widgets\test_speech_to_text.py' --dev --show`. 

`Error rendering Bokeh items: TypeError: c is not a constructor`

image

My hypothesis is that it has nothing to do with this PR.

Next step is on you @philippjfr . Let me know if there is more I can/ shall do?

**Comment by philippjfr** [comment]
Thanks, I'll take a look.

**Comment by philippjfr** [comment]
Thanks @MarcSkovMadsen!

**Pull request merged**
