### PR TITLE
Add ChatFeed reference notebook

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
I intend to make a first draft to get into Andrews big chat PR

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Please take a look @ahuang11 

You are welcome to either merge now and we can improve later or give me some directions to how you would like this notebook to end up. Thanks

**Comment by ahuang11** [comment]
Thanks for getting it started. I'm currently away from my computer, but I can take a look later. Do you mind if I make pushes to this branch?

**Comment by MarcSkovMadsen** [comment]
Push away

**Comment by ahuang11** [comment]
Pushed some updates; still working on it, but have been busy today.

**Comment by MarcSkovMadsen** [comment]
I've merged and pushed more things.

**Comment by ahuang11** [comment]
I revised the notebook again; I think I'm happy with where it's at now.

Planning to merge now so that the two PRs don't diverge; feel free to make comments in the chat_components branch!

**Comment by MarcSkovMadsen** [comment]
Love that we can collaborate on things in a separate PR and get them in before they get to big or diverge. Thanks.

**Pull request merged**
