### PR TITLE
Bump perspective version to 2.8.0

### PR DESCRIPTION
**Pull request by limx0**
Perspective has gone through some nice UX updates and bug fixes since the version panel is currently on (1.9.2). 

Would it be possible to bump up to the latest version?

### CODE REVIEW

**Comment by limx0** [comment]
Currently failing on: 

```
Error rendering Bokeh items: TypeError: Cannot read properties of undefined (reading 'worker')
    at v.render (panel.min.js?v=c47f5b18b8a430e698b9fe15e51f6119984e78334bcf3f45e210d30c37ef2f9e:130:3763)
    at c.render (bokeh.min.js?v=3ca6425586de5036dc01992dd69aa61e9196dd02619557cfaeb1b3d8b77adf724be49401b1168483d165494ce57a6daa16e6f6d3660fef117d45028221f86357:554:2239)
    at c.render (panel.min.js?v=c47f5b18b8a430e698b9fe15e51f6119984e78334bcf3f45e210d30c37ef2f9e:51:1136)
    at c.render (bokeh.min.js?v=3ca6425586de5036dc01992dd69aa61e9196dd02619557cfaeb1b3d8b77adf724be49401b1168483d165494ce57a6daa16e6f6d3660fef117d45028221f86357:554:2239)
    at c.render (bokeh.min.js?v=3ca6425586de5036dc01992dd69aa61e9196dd02619557cfaeb1b3d8b77adf724be49401b1168483d165494ce57a6daa16e6f6d3660fef117d45028221f86357:554:2239)
    at c.render (panel.min.js?v=c47f5b18b8a430e698b9fe15e51f6119984e78334bcf3f45e210d30c37ef2f9e:51:1136)
    at c.render_to (bokeh.min.js?v=3ca6425586de5036dc01992dd69aa61e9196dd02619557cfaeb1b3d8b77adf724be49401b1168483d165494ce57a6daa16e6f6d3660fef117d45028221f86357:554:6277)
    at bokeh.min.js?v=3ca6425586de5036dc01992dd69aa61e9196dd02619557cfaeb1b3d8b77adf724be49401b1168483d165494ce57a6daa16e6f6d3660fef117d45028221f86357:218:375
    at async f (bokeh.min.js?v=3ca6425586de5036dc01992dd69aa61e9196dd02619557cfaeb1b3d8b77adf724be49401b1168483d165494ce57a6daa16e6f6d3660fef117d45028221f86357:218:198)
    at async t.add_document_standalone (bokeh.min.js?v=3ca6425586de5036dc01992dd69aa61e9196dd02619557cfaeb1b3d8b77adf724be49401b1168483d165494ce57a6daa16e6f6d3660fef117d45028221f86357:218:459)
```

**Comment by limx0** [comment]
Hey @philippjfr sorry for the confusion. This is breaking on this PR and needs to be fixed.

**Comment by philippjfr** [comment]
Not quite done here. There's two tasks remaining

1. Figure out if we can bundle the Perspective code somehow
2. Figure out why the console error related to syncing some option happens

**Review by philippjfr — APPROVED** [review]

**Comment by limx0** [comment]
Thanks @philippjfr !

**Pull request merged**
