### PR TITLE
Add matplotlib guidance to reference pane

### PR DESCRIPTION
**Pull request by maximlt**
Fixes https://github.com/holoviz/panel/issues/509

I found VSCode to be quite handy in working with notebooks and diffing them. It helped me to make sure I haven't added any metadata :)

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks, I think this makes a lot of sense. That said, I was still having issues with the inline backend popping up the figure if you don't set `matplotlib.use('agg')`. You're not seeing that.

**Comment by maximlt** [comment]
Hi!
No I haven't noticed the inline backend popping up the figure in a notebook.
I've just tried again to test that and found something weird. The notebook runs fine in the classic notebook. In Lab however the figure isn't updated when the object is changed. I've tried with displaying the pane with `.servable()`, same bug. It works well only if I serve the pane with `.show()`. Would you like me to open an issue for that?

**Comment by philippjfr** [comment]
Yes, let's open an issue.

**Comment by maximlt** [comment]
Just tried again and it's working now in Lab on *master*. I don't know what went wrong but things seem to be alright now :)

**Pull request merged**
