### PR TITLE
Added FastApi in the user guide for embedding apps

### PR DESCRIPTION
**Pull request by t-houssian**
I created a tutorial to embed panel apps in fastAPI, I created the tutorial in jupyter lab and formatted similarly to the django tutorial. I also added the examples in `panel/examples/apps/fastApi`. Let me know if there is anything else I need to update, add, or change and I'll get on it.

### CODE REVIEW

**Comment by philippjfr** [comment]
This is sooo exciting. Thanks @t-houssian! I'll probably merge now and then follow up subsequently and quiz you on that PR.

**Comment by MarcSkovMadsen** [comment]
When will we see it in the docs :-)  Can't wait. Thanks @t-houssian.

One idea could be to add an example of an REST API endpoint and showing the Open API docs. 

For me that is really powerful.

And if in general there is some key of advantage (performance) of running on Fast API vs. Bokeh/ Panel server or the opposite it would be nice to know.

**Comment by khannaum** [comment]
fastAPI  makes remote browser loading fast

https://panel.holoviz.org/user_guide/FastApi_Apps.html?highlight=fastapi

**no HTML link provided  in the main page**
https://panel.holoviz.org/user_guide/

image

**Comment by philippjfr** [comment]
Thanks for catching that!

**Pull request merged**
