### PR TITLE
Improve VTK tests and coverage

### PR DESCRIPTION
**Pull request by xavArtley**

### CODE REVIEW

**Comment by philippjfr** [comment]
Looks like there's a py2 issue:

```
        for renderer in renderers:
            for renProp in renderer.GetViewProps():
>               if not renProp.GetVisibility() or not isinstance(renProp, vtk.vtkActor):
E               AttributeError: 'module' object has no attribute 'vtkActor'
```

Sorry about still having to deal with py2 issues, excited to drop it soon.

**Comment by xavArtley** [comment]
It will be hard for me to debug since there is no vtk binaries for python 2 for windows
I can found binaries but only for vtk-7.1

**Comment by xavArtley** [comment]
when using `import vtk` in python 2.7 result in `panel.pane.vtk.vtk`

**Comment by philippjfr** [comment]
Thanks again, you rock!

**Pull request merged**
