### PR TITLE
Make `--setup`/`--autoreload`/`--warm` work with `--num-procs`

### LINKED ISSUE #6816: Panel --num-procs value leads to Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists') error
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
Python version        :  3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
IPython version       :  8.24.0
Tornado version       :  6.4
Bokeh version         :  3.4.1
BokehJS static path   :  /conda_envs/pyviz_env/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  v21.7.3
npm version           :  10.5.0
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.8.0-31-generic-x86_64-with-glibc2.39

#### Description of expected behavior and the observed behavior
On running the following code with the panel serve command, note the `--num-procs` is set,
I get the following error. If I remove the num_procs, it works.

`panel serve needles_and_the_haystack.py --num-procs 10 --autoreload`

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks
# FILENAME  : needles_and_the_haystack.py

import holoviews as hv
import panel as pn
import pandas as pd
import datashader as ds
import colorcet

df = pd.read_parquet('./data/gulls.parq') # Small for datashader, big for other approaches!
print(f'There are {len(df)/1e6:.2f} million samples in this dataset')
print(f'The columns of this dataframe are: {", ".join(df.columns)}')

print(df.head())

template = pn.template.FastListTemplate(title="Gull tracking dashboard")
esri = hv.element.tiles.ESRI().redim(x='easting', y='northing').opts(xlim=(1.5e4,4.22e5), ylim=(6.25e6,6.7e6))
points = hv.Points(df, kdims=['easting', 'northing'])
raster = hv.operation.datashader.rasterize(points, selector=ds.max("height-above-msl")).opts(
    tools=["hover"], colorbar=True, cmap=colorcet.CET_L4,  responsive=True, cnorm="eq_hist")
overlay = esri * raster.opts(cmap='fire', cnorm='eq_hist', min_height=400)
description = """
This dashboard shows how easy it is to go from an aggregate view of 2.4 million points
down to the details of a single GPS sample.
"""
template.main.append(pn.Column(description, overlay, sizing_mode='stretch_both' ))
template.servable()


```

#### Stack traceback and/or browser JavaScript console output

There are 2.42 million samples in this dataset
The columns of this dataframe are: longitude, latitude, temperature, heading, height-above-msl, easting, northing
       longitude   latitude  temperature     heading  height-above-msl        easting      northing
index                                                                                              
0       2.819559  50.978461         28.5  220.322155              -7.0  313871.827614  6.617485e+06
1       2.819568  50.978458         33.7  219.465066              -3.0  313872.885149  6.617484e+06
2       2.819568  50.978466         33.5  121.618779              -3.0  313872.918545  6.617486e+06
3       2.819576  50.978476         34.3  121.923660              -2.0  313873.797969  6.617487e+06
4       2.819571  50.978457         32.5  306.500706               0.0  313873.219107  6.617484e+06
2024-05-09 15:02:23,110 Starting Bokeh server version 3.4.1 (running on Tornado 6.4)
2024-05-09 15:02:23,111 User authentication hooks NOT provided (default user enabled)
2024-05-09 15:02:23,125 Bokeh app running at: http://localhost:5006/needles_and_the_haystack
2024-05-09 15:02:23,125 Starting Bokeh server with process id: 27705
/mnt/WindowsData/LinuxFiles/conda_envs/pyviz_env/lib/python3.11/site-packages/panel/io/reload.py:131: FutureWarning: --autoreload functionality now depends on the watchfiles library. In future versions autoreload will not work without watchfiles being installed. Since it provides a much better user experience consider installing it today.
  warnings.warn(
2024-05-09 15:02:23,132 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,141 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,149 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,157 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,166 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,176 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,186 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,197 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,208 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,673 child 5 (pid 27710) exited with status 1, restarting
2024-05-09 15:02:23,689 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,694 child 1 (pid 27706) exited with status 1, restarting
2024-05-09 15:02:23,707 child 2 (pid 27707) exited with status 1, restarting
2024-05-09 15:02:23,708 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,719 child 3 (pid 27708) exited with status 1, restarting
2024-05-09 15:02:23,720 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,728 child 4 (pid 27709) exited with status 1, restarting
2024-05-09 15:02:23,730 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,738 child 6 (pid 27711) exited with status 1, restarting
2024-05-09 15:02:23,739 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,748 child 7 (pid 27712) exited with status 1, restarting
2024-05-09 15:02:23,749 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,759 child 8 (pid 27713) exited with status 1, restarting
2024-05-09 15:02:23,760 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,769 child 9 (pid 27714) exited with status 1, restarting
2024-05-09 15:02:23,771 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:23,782 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,255 child 5 (pid 27722) exited with status 1, restarting
2024-05-09 15:02:24,268 child 1 (pid 27723) exited with status 1, restarting
2024-05-09 15:02:24,269 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,280 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,283 child 6 (pid 27727) exited with status 1, restarting
2024-05-09 15:02:24,294 child 3 (pid 27725) exited with status 1, restarting
2024-05-09 15:02:24,295 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,301 child 4 (pid 27726) exited with status 1, restarting
2024-05-09 15:02:24,303 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,310 child 2 (pid 27724) exited with status 1, restarting
2024-05-09 15:02:24,311 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,318 child 7 (pid 27728) exited with status 1, restarting
2024-05-09 15:02:24,319 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,327 child 8 (pid 27729) exited with status 1, restarting
2024-05-09 15:02:24,329 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,337 child 9 (pid 27730) exited with status 1, restarting
2024-05-09 15:02:24,338 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,348 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,832 child 5 (pid 27738) exited with status 1, restarting
2024-05-09 15:02:24,839 child 4 (pid 27742) exited with status 1, restarting
2024-05-09 15:02:24,840 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,846 child 1 (pid 27739) exited with status 1, restarting
2024-05-09 15:02:24,847 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,852 child 2 (pid 27743) exited with status 1, restarting
2024-05-09 15:02:24,853 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,858 child 3 (pid 27741) exited with status 1, restarting
2024-05-09 15:02:24,859 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,863 child 8 (pid 27745) exited with status 1, restarting
2024-05-09 15:02:24,864 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,869 child 6 (pid 27740) exited with status 1, restarting
2024-05-09 15:02:24,870 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,874 child 7 (pid 27744) exited with status 1, restarting
2024-05-09 15:02:24,876 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,882 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:24,887 child 9 (pid 27746) exited with status 1, restarting
2024-05-09 15:02:24,896 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,380 child 4 (pid 27748) exited with status 1, restarting
2024-05-09 15:02:25,389 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,396 child 5 (pid 27747) exited with status 1, restarting
2024-05-09 15:02:25,405 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,405 child 1 (pid 27749) exited with status 1, restarting
2024-05-09 15:02:25,414 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,419 child 2 (pid 27750) exited with status 1, restarting
2024-05-09 15:02:25,425 child 8 (pid 27752) exited with status 1, restarting
2024-05-09 15:02:25,426 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,432 child 6 (pid 27753) exited with status 1, restarting
2024-05-09 15:02:25,433 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,439 child 3 (pid 27751) exited with status 1, restarting
2024-05-09 15:02:25,440 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,446 child 7 (pid 27754) exited with status 1, restarting
2024-05-09 15:02:25,447 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,454 child 9 (pid 27755) exited with status 1, restarting
2024-05-09 15:02:25,455 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,463 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,947 child 5 (pid 27764) exited with status 1, restarting
2024-05-09 15:02:25,953 child 4 (pid 27763) exited with status 1, restarting
2024-05-09 15:02:25,955 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,959 child 2 (pid 27766) exited with status 1, restarting
2024-05-09 15:02:25,960 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,966 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,970 child 1 (pid 27765) exited with status 1, restarting
2024-05-09 15:02:25,977 child 7 (pid 27770) exited with status 1, restarting
2024-05-09 15:02:25,979 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,984 child 8 (pid 27767) exited with status 1, restarting
2024-05-09 15:02:25,985 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,991 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:25,998 child 6 (pid 27768) exited with status 1, restarting
2024-05-09 15:02:26,005 child 3 (pid 27769) exited with status 1, restarting
2024-05-09 15:02:26,006 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,013 child 9 (pid 27771) exited with status 1, restarting
2024-05-09 15:02:26,014 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,022 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,514 child 5 (pid 27772) exited with status 1, restarting
2024-05-09 15:02:26,521 child 2 (pid 27774) exited with status 1, restarting
2024-05-09 15:02:26,522 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,529 child 4 (pid 27773) exited with status 1, restarting
2024-05-09 15:02:26,530 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,536 child 1 (pid 27775) exited with status 1, restarting
2024-05-09 15:02:26,537 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,543 child 7 (pid 27776) exited with status 1, restarting
2024-05-09 15:02:26,544 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,551 child 8 (pid 27777) exited with status 1, restarting
2024-05-09 15:02:26,552 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,561 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,569 child 6 (pid 27778) exited with status 1, restarting
2024-05-09 15:02:26,578 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,583 child 9 (pid 27780) exited with status 1, restarting
2024-05-09 15:02:26,591 child 3 (pid 27779) exited with status 1, restarting
2024-05-09 15:02:26,593 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:26,601 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,070 child 4 (pid 27790) exited with status 1, restarting
2024-05-09 15:02:27,079 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,096 child 8 (pid 27793) exited with status 1, restarting
2024-05-09 15:02:27,104 child 5 (pid 27788) exited with status 1, restarting
2024-05-09 15:02:27,106 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,111 child 2 (pid 27789) exited with status 1, restarting
2024-05-09 15:02:27,112 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,119 child 1 (pid 27791) exited with status 1, restarting
2024-05-09 15:02:27,120 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,126 child 3 (pid 27796) exited with status 1, restarting
2024-05-09 15:02:27,127 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,133 child 7 (pid 27792) exited with status 1, restarting
2024-05-09 15:02:27,134 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,140 child 6 (pid 27794) exited with status 1, restarting
2024-05-09 15:02:27,141 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,148 child 9 (pid 27795) exited with status 1, restarting
2024-05-09 15:02:27,149 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,157 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,651 child 4 (pid 27797) exited with status 1, restarting
2024-05-09 15:02:27,659 child 6 (pid 27804) exited with status 1, restarting
2024-05-09 15:02:27,659 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,666 child 8 (pid 27798) exited with status 1, restarting
2024-05-09 15:02:27,667 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,673 child 5 (pid 27799) exited with status 1, restarting
2024-05-09 15:02:27,674 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,680 child 7 (pid 27803) exited with status 1, restarting
2024-05-09 15:02:27,681 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,687 child 2 (pid 27800) exited with status 1, restarting
2024-05-09 15:02:27,688 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,694 child 1 (pid 27801) exited with status 1, restarting
2024-05-09 15:02:27,695 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,702 child 3 (pid 27802) exited with status 1, restarting
2024-05-09 15:02:27,703 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,709 child 9 (pid 27805) exited with status 1, restarting
2024-05-09 15:02:27,711 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:27,718 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,219 child 4 (pid 27813) exited with status 1, restarting
2024-05-09 15:02:28,226 child 5 (pid 27816) exited with status 1, restarting
2024-05-09 15:02:28,227 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,233 child 6 (pid 27814) exited with status 1, restarting
2024-05-09 15:02:28,234 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,240 child 8 (pid 27815) exited with status 1, restarting
2024-05-09 15:02:28,241 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,248 child 7 (pid 27817) exited with status 1, restarting
2024-05-09 15:02:28,249 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,255 child 9 (pid 27821) exited with status 1, restarting
2024-05-09 15:02:28,256 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,264 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,265 child 3 (pid 27820) exited with status 1, restarting
2024-05-09 15:02:28,274 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,278 child 2 (pid 27818) exited with status 1, restarting
2024-05-09 15:02:28,285 child 1 (pid 27819) exited with status 1, restarting
2024-05-09 15:02:28,287 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,295 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,751 child 4 (pid 27822) exited with status 1, restarting
2024-05-09 15:02:28,760 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,772 child 5 (pid 27823) exited with status 1, restarting
2024-05-09 15:02:28,780 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,798 child 6 (pid 27824) exited with status 1, restarting
2024-05-09 15:02:28,806 child 9 (pid 27827) exited with status 1, restarting
2024-05-09 15:02:28,806 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,813 child 8 (pid 27825) exited with status 1, restarting
2024-05-09 15:02:28,815 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,821 child 7 (pid 27826) exited with status 1, restarting
2024-05-09 15:02:28,822 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,830 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,834 child 3 (pid 27835) exited with status 1, restarting
2024-05-09 15:02:28,842 child 2 (pid 27836) exited with status 1, restarting
2024-05-09 15:02:28,843 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,851 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:28,855 child 1 (pid 27837) exited with status 1, restarting
2024-05-09 15:02:28,864 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,290 child 5 (pid 27839) exited with status 1, restarting
2024-05-09 15:02:29,299 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,318 child 4 (pid 27838) exited with status 1, restarting
2024-05-09 15:02:29,327 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,330 child 6 (pid 27840) exited with status 1, restarting
2024-05-09 15:02:29,339 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,353 child 8 (pid 27842) exited with status 1, restarting
2024-05-09 15:02:29,362 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,379 child 7 (pid 27843) exited with status 1, restarting
2024-05-09 15:02:29,388 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,389 child 3 (pid 27844) exited with status 1, restarting
2024-05-09 15:02:29,397 child 9 (pid 27841) exited with status 1, restarting
2024-05-09 15:02:29,398 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,406 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,406 child 1 (pid 27846) exited with status 1, restarting
2024-05-09 15:02:29,414 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,437 child 2 (pid 27845) exited with status 1, restarting
2024-05-09 15:02:29,446 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,857 child 5 (pid 27854) exited with status 1, restarting
2024-05-09 15:02:29,866 Cannot start Bokeh server [EEXIST]: FileExistsError(17, 'File exists')
2024-05-09 15:02:29,899 child 4 (pid 27855) exited with status 1, restarting
ERROR: Too many child restarts, giving up

#### Screenshots or screencasts of the bug in action

- [ ] I may be interested in making a pull request to address this

### LINKED ISSUE #6891: OSError when serving simple panel app with --num-procs and --setup
#### ALL software version info
```
(.env) [duarteocarmo:~/Repos/panel-bug]$ sw_vers                                                                                                                                            
ProductName:            macOS
ProductVersion:         14.4.1
BuildVersion:           23E224
```

```
(.env) [duarteocarmo:~/Repos/panel-bug]$ pip freeze | grep 'panel'                                                                                                                          
panel==1.4.4
(.env) [duarteocarmo:~/Repos/panel-bug]$ python                                                                                                                                             
Python 3.10.11 (main, May 12 2023, 08:35:23) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
```

#### Description of expected behavior and the observed behavior
When running panel serve with both the `--setup` and `--num-procs`. 

However, when running the app with either the `num-procs` or `setup`options isolated, it works. When combined, I get this error. 

```
panel serve app.py --setup background-job.py --num-procs 2
```

I receive the following error:

```
(.env) [duarteocarmo:~/Repos/panel-bug]$ panel serve app.py --setup background-job.py --num-procs 2                                                                                         
2024-06-04 15:06:37,885 Starting Bokeh server version 3.4.1 (running on Tornado 6.4)
2024-06-04 15:06:37,887 User authentication hooks NOT provided (default user enabled)
2024-06-04 15:06:37,893 Cannot start Bokeh server [EBADF]: OSError(9, 'Bad file descriptor')
2024-06-04 15:06:37,893 Cannot start Bokeh server [EBADF]: OSError(9, 'Bad file descriptor')
2024-06-04 15:06:38,072 child 0 (pid 43398) exited with status 1, restarting
2024-06-04 15:06:38,075 child 1 (pid 43399) exited with status 1, restarting
2024-06-04 15:06:38,079 Cannot start Bokeh server [EBADF]: OSError(9, 'Bad file descriptor')
2024-06-04 15:06:38,079 Cannot start Bokeh server [EBADF]: OSError(9, 'Bad file descriptor')
2024-06-04 15:06:38,235 child 1 (pid 43401) exited with status 1, restarting
```

#### Complete, minimal, self-contained example code that reproduces the issue

```python
# app.py
import panel as pn


pn.pane.Markdown("Hello World").servable()
```
```python
# background_job.py
from datetime import datetime

import panel as pn

current_time = datetime.now()

def task() -> None:
    """Refresh the data in the database."""
    print("Ran task")

pn.state.schedule_task(name="load_data", callback=task, at=current_time, period="2m")
```

Now run:
```
panel serve app.py --setup background-job.py --num-procs 2
```

#### Stack traceback and/or browser JavaScript console output

```
2024-06-04 15:09:51,223 Starting Bokeh server version 3.4.1 (running on Tornado 6.4)
2024-06-04 15:09:51,224 User authentication hooks NOT provided (default user enabled)
2024-06-04 15:09:51,230 Cannot start Bokeh server [EBADF]: OSError(9, 'Bad file descriptor')
2024-06-04 15:09:51,230 Cannot start Bokeh server [EBADF]: OSError(9, 'Bad file descriptor')
2024-06-04 15:09:51,392 child 1 (pid 46545) exited with status 1, restarting
2024-06-04 15:09:51,397 Cannot start Bokeh server [EBADF]: OSError(9, 'Bad file descriptor')
2024-06-04 15:09:51,399 child 0 (pid 46544) exited with status 1, restarting
2024-06-04 15:09:51,403 Cannot start Bokeh server [EBADF]: OSError(9, 'Bad file descriptor')
2024-06-04 15:09:51,555 child 0 (pid 46547) exited with status 1, restarting
2024-06-04 15:09:51,559 child 1 (pid 46546) exited with status 1, restarting
2024-06-04 15:09:51,562 Cannot start Bokeh server [EBADF]: OSError(9, 'Bad file descriptor')
2024-06-04 15:09:51,564 Cannot start Bokeh server [EBADF]: OSError(9, 'Bad file descriptor')
```

- [x] I may be interested in making a pull request to address this (if given some guidance)

### PR DESCRIPTION
**Pull request by hoxbro**
Resolves #6891 
Resolves #6816

The following `generate_session(app, initialize=True)` gave file errors on Python versions below 3.12, so I have set initialize to False for those versions. I'm not entirely sure why it works fine on Python 3.12, but it could be related to sub-interpreters. 

Postpone the setup script execution after the server starts. This means the setup script runs for each process; for example, it will run twice for the following example. 

``` python 
# app.py
import panel as pn

pn.pane.Markdown("Hello World").servable()
```

``` python
# background_job.py
from datetime import datetime
import os
import panel as pn

current_time = datetime.now()


def task() -> None:
    """Refresh the data in the database."""
    print(f"Ran task at {datetime.now()} (PID {os.getpid()})")


pn.state.schedule_task(name="load_data", callback=task, at=current_time, period="5s")
```

Command: `panel serve app.py --setup background_job.py --num-procs 2`

https://github.com/holoviz/panel/assets/19758978/035e6f2d-269d-49a2-a46a-38669f793a92

Also tested:

`panel serve app.py --num-procs 2 --warm`
`panel serve app.py --num-procs 2 --autoreload`

### CODE REVIEW

**Review by philippjfr — APPROVED** [review]
This makes a lot sense to me. What's missing here, apart from tests?

**Comment by hoxbro** [comment]
> What's missing here, apart from tests?

Time :upside_down_face: This does not fix the problem observed on older versions of Python. It could, therefore, be that the loading of the file should also be postponed.

**Comment by philippjfr** [comment]
>This does not fix the problem observed on older versions of Python.

How old are we talking?

**Comment by hoxbro** [comment]
Only working with Python 3.12, IIRC.

**Comment by MarcSkovMadsen** [comment]
Would this fix the --warm issue too?

**Comment by hoxbro** [comment]
> Would this fix the --warm issue too?

Yes, it should be the case after the changes I made yesterday.

**Review by philippjfr — APPROVED** [review]

**Comment by instance01** [comment]
@MarcSkovMadsen @philippjfr - we relied on the setup script to be run before the server starts. This reduces some of the usefuleness of the setup script.

It is also still mentioned in the wiki "--setup SETUP         Path to a setup script to run before server starts.". Might want to update the documentation to reflect that this is not supported any longer. Link to the documentation: https://panel.holoviz.org/how_to/server/commandline.html

**Pull request merged**
