### PR TITLE
Added FontAwesome icon and pane

### PR DESCRIPTION
**Pull request by philippjfr**
```python
modifiers = ['', 'fa-spin']
sizes = ['' 'fa-2x', 'fa-5x', 'fa-10x']
icons = ['fa-spinner', 'fa-cog', 'fa-heart', 'fa-clock', 'fa-check', 'fa-home', 'fa-volume-up']

pn.GridBox(*[pn.panel(' '.join([i, s, m]), margin=20) for m in modifiers for s in sizes for i in icons], ncols=10).show()

pn.Column(*((pn.pane.Markdown('# Buttons'),)+tuple(pn.widgets.Button(icon='%s fa-2x' % i) for i in icons))).show()
```

fa

Screen Shot 2019-12-18 at 8 07 47 PM

### CODE REVIEW

**Comment by jbednar** [comment]
Cool! Is it possible to make the button resize to match the icon's size?  And could it be possible to make the button itself disappear as an option, leaving only the icon (but still clickable)?

**Comment by philippjfr** [comment]
>Is it possible to make the button resize to match the icon's size?

That's already what it does.

>And could it be possible to make the button itself disappear as an option, leaving only the icon (but still clickable)?

Probably using some css tricks which I could expose as a parameter on buttons.

**Comment by jbednar** [comment]
That's not what it's doing above (horizontally)...

**Comment by philippjfr** [comment]
>That's not what it's doing above (horizontally)...

Oh, right, currently the widgets default to width=300, it's possible it'll do the right thing with width=None. Will give it a spin later.

**Comment by philippjfr** [comment]
Going to close, you can easily add FontAwesome icons with ReactiveHTML now and this PR is beyond hope.

**Pull request closed without merging**
