### PR TITLE
Finish CDN migration

### PR DESCRIPTION
**Pull request by philippjfr**
Use `config.npm_cdn` for template resources.

### CODE REVIEW

**Comment by Hoxbro** [comment]
After this PR Lumen Builder looks like this:

image

``` console
2022-09-26 11:24:40,970 Starting Bokeh server version 2.4.3 (running on Tornado 6.2)
2022-09-26 11:24:40,970 User authentication hooks NOT provided (default user enabled)
2022-09-26 11:24:40,972 Bokeh app running at: http://localhost:5006/ui
2022-09-26 11:24:40,972 Starting Bokeh server with process id: 69777
2022-09-26 11:24:42,993 W-1002 (EMPTY_LAYOUT): Layout has no children: Column(id='1015', ...)
2022-09-26 11:24:43,101 404 GET /static/extensions/panel/bundled/js/@microsoft/fast-colors@5.3.1/dist/index.js (127.0.0.1) 0.61ms
2022-09-26 11:24:43,102 404 GET /static/extensions/panel/bundled/js/@microsoft/fast-components@1.21.8/dist/fast-components.js (127.0.0.1) 0.66ms
2022-09-26 11:24:43,330 WebSocket connection opened
2022-09-26 11:24:43,331 ServerConnection created
```

**Comment by philippjfr** [comment]
Are you on Panel master? I cannot reproduce.

**Comment by Hoxbro** [comment]
Yes. Both on panel and lumen.

**Comment by philippjfr** [comment]
You'll have to fetch the latest resources by rerunning an editable install on Panel.

**Comment by philippjfr** [comment]
Alternatively you can also just run `panel.compiler.bundle_resources()`

**Comment by Hoxbro** [comment]
It works now. 

I needed to run `python setup.py develop`. `python -m pip install --no-build-isolation --no-deps -e .` was not enough.

**Comment by philippjfr** [comment]
>python -m pip install --no-build-isolation --no-deps -e . was not enough.

Probably due to latest pip nonsense. Setting this probably would have done it:

>SETUPTOOLS_ENABLE_FEATURES: "legacy-editable"

**Comment by arifin-chemist89** [comment]
Just found that https://github.com/holoviz/panel/blob/bdf2742679fb16861b8432872aadb0ed3baddda7/panel/_templates/index.html still using the CDN from https://cdn.holoviz.org/panel/latest/dist/bundled/js/, instead of https://cdn.jsdelivr.net/npm.

**Comment by philippjfr** [comment]
cdn.holoviz.org is what it should be using.

**Comment by philippjfr** [comment]
Neither unpkg nor jsdelivr are recommended for production usage so we decided to maintain our own CDN.

**Pull request merged**
