### PR TITLE
Add ability to configure exception handler

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes https://github.com/holoviz/panel/issues/3574
Fixes https://github.com/holoviz/panel/issues/3893

### CODE REVIEW

**Comment by philippjfr** [comment]
Not handling that in this PR.

**Comment by MarcSkovMadsen** [comment]
Makes sense, will be a big improvement already.

**Comment by philippjfr** [comment]
Question for you @MarcSkovMadsen. Should the handler accept just the exception or should it also get the event that caused the exception?

**Comment by MarcSkovMadsen** [comment]
If it does not slow down Panel I think it should provide both the exception and the event because it would be hard to change the api later.

For my current use case I only need the exception.

**Comment by philippjfr** [comment]
Looks like I have to punt on that anyway because it's a ton of work to make that information available in all cases.

**Comment by philippjfr** [comment]
In future I can search for an explicit `event` argument in the signature and add it without breaking backward compatibility.

**Comment by MarcSkovMadsen** [comment]
I just tested the main branch and it works as expected for me. You can find the test example code and a demo video in https://github.com/holoviz/panel/issues/3897#issue-1389402544.

**Comment by MarcSkovMadsen** [comment]
There is a `.gif` for the release blog post here

panel-exception-handling

```python
import logging
import panel as pn

def exception_handler(ex):
    logging.error("Error", exc_info=ex)
    pn.state.notifications.error(f'{ex}')

pn.extension(exception_handler=exception_handler, notifications=True, template="fast")

pn.state.template.param.update(site="Awesome Panel", title="Easy and powerful exception handling added for production apps")

button = pn.widgets.Button(name="Raise Exception").servable()

def raise_exception(_=None):
    raise ValueError(f"Something went wrong when clicking the button")

button.on_click(raise_exception)

slider = pn.widgets.IntSlider(value=0, start=0, end=5, name="Raise exception on 3").servable()

@pn.depends(value=slider, watch=True)
def _raise_exception_2(value):
    if value==3:
        raise ValueError("Some slider error")

pn.pane.Markdown("""
```python
import logging
import panel as pn

def exception_handler(ex):
    logging.error("Error", exc_info=ex)
    pn.state.notifications.error(f'{ex}')

pn.extension(exception_handler=exception_handler, notifications=True, template="fast")
```
""").servable()
```

**Pull request merged**
