### PR TITLE
Improve layout sizing mode inheritance

### PR DESCRIPTION
**Pull request by philippjfr**
- Fixes logic computing min_width and min_height
- Fixes logic resolving expanded sizing mode correctly

### CODE REVIEW

**Comment by philippjfr** [comment]
Errors are all related to an hvPlot issue which has now been resolved, will merge.

**Comment by Hoxbro** [comment]
After this PR I get the following interactive plot...

``` python
import xarray as xr
import hvplot.xarray  # noqa

air_ds = xr.tutorial.open_dataset('air_temperature').load()
air = air_ds.air
air_ds
air_ds.air.hvplot(groupby='time')
```

image

**Comment by philippjfr** [comment]
Interesting, before it's correctly aligned?

**Comment by Hoxbro** [comment]
Yes:
image

**Pull request merged**
