### PR TITLE
Unify recursive update on ReplacementPane

### LINKED ISSUE #4951: ValueError on one-element dataframes: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
panel 1.0.3:

The following minimal example does not work - the second panel does not update when the select buttom is changed. May be related to #4950 

```
import panel as pn
import xarray as xr
import pandas as pd

da = xr.DataArray(np.arange(56).reshape((7, 8)), dims=["x", "y"],name='test')

minimal = pn.widgets.Select(name='test', options=[1,2,3],value=1)
@pn.depends(minimal)
def show_value_works(value):
    return pn.pane.DataFrame(da.to_dataframe())

@pn.depends(minimal)
def show_value_fails(value):
    return pn.pane.DataFrame(da.sel(x=[value],y=[value]).to_dataframe())

layout = pn.Row(minimal,show_value_works,show_value_fails)
layout.servable()
```

error output:
```

2023-05-26 17:34:21,364 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f4c34cd8190>>, <Task finished name='Task-14221' coro=<ServerSession.with_document_locked() done, defined at /home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/bokeh/server/session.py:77> exception=ValueError('The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().')>)
Traceback (most recent call last):
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/tornado/ioloop.py", line 738, in _run_callback
    ret = callback()
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/tornado/ioloop.py", line 762, in _discard_future_result
    future.result()
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/bokeh/server/session.py", line 98, in _needs_document_lock_wrapper
    result = await result
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/panel/reactive.py", line 424, in _change_coroutine
    state._handle_exception(e)
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/panel/io/state.py", line 432, in _handle_exception
    raise exception
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/panel/reactive.py", line 422, in _change_coroutine
    self._change_event(doc)
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/panel/reactive.py", line 440, in _change_event
    self._process_events(events)
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/panel/reactive.py", line 379, in _process_events
    self.param.update(**self_events)
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/param/parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/panel/param.py", line 827, in _replace_pane
    self._update_inner(new_object)
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/panel/pane/base.py", line 700, in _update_inner
    new_pane, internal = self._update_from_object(
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/panel/pane/base.py", line 666, in _update_from_object
    if not equal:
  File "/home/it-499/mambaforge/envs/pavics/lib/python3.8/site-packages/pandas/core/generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

```

### PR DESCRIPTION
**Pull request by Hoxbro**
Fixes #4951
Fixes https://github.com/holoviz/panel/issues/4968

### CODE REVIEW

**Comment by Hoxbro** [comment]
I think it would be beneficial to have `_generate_hash` as a fallback and do the simple equally check first.  Mainly because it `_generate_hash` is significantly slower for most cases.  

Maybe even have a `.all()` try before using it.

**Comment by philippjfr** [comment]
My thinking was that in most cases the cost is neglible but in the case of a dataframe where the cost does potentially matter significantly equal won't work anyway so you end up paying the cost twice.

**Comment by philippjfr** [comment]
My thinking was that in most cases the cost is neglible but in the case of a dataframe where the cost does potentially matter significantly equal won't work anyway so you end up paying the cost twice.

The .all() could help with that. Not sure I prefer it though.

**Comment by philippjfr** [comment]
Fair points, swapped the order.

**Pull request merged**
