### PR TITLE
Add different versions of Python back to the CI

### PR DESCRIPTION
**Pull request by Hoxbro**
Adding tests back for other Python versions for the test CI, and other small fixes related to the test suite.

### CODE REVIEW

**Comment by Hoxbro** [comment]
The ipywidget test fails right now and can be recreated with this:

I can't recreate it with pure Bokeh. 

``` python
import panel as pn

pane = pn.pane.Str("A")
with pn.config.set(comms="ipywidgets"):
    data, metadata = pane._repr_mimebundle_()
    data, metadata = pane._repr_mimebundle_()
```

``` python-traceback
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 6
      4 with pn.config.set(comms="ipywidgets"):
      5     data, metadata = pane._repr_mimebundle_()
----> 6     data, metadata = pane._repr_mimebundle_()

File ~/Repos/holoviz/panel/panel/viewable.py:674, in Viewable._repr_mimebundle_(self, include, exclude)
    671     loaded = hv.extension._loaded
    673 if config.comms in ('vscode', 'ipywidgets'):
--> 674     widget = ipywidget(self)
    675     if hasattr(widget, '_repr_mimebundle_'):
    676         return widget._repr_mimebundle_(include=include, exclude=exclude), {}

File ~/Repos/holoviz/panel/panel/io/notebook.py:455, in ipywidget(obj, doc, **kwargs)
    452 from ..pane import panel
    454 model = panel(obj.clone(), **kwargs).get_root(doc=doc, preprocess=False)
--> 455 widget = BokehModel(model._clone(), combine_events=True)
    456 if hasattr(widget, '_view_count'):
    457     widget._view_count = 0

File ~/Repos/holoviz/jupyter_bokeh/jupyter_bokeh/widgets.py:70, in BokehModel.__init__(self, model, **kwargs)
     68 def __init__(self, model, **kwargs):
     69     assert isinstance(model, LayoutDOM)
---> 70     self.update_from_model(model)
     71     super(BokehModel, self).__init__(**kwargs)
     72     self.on_msg(self._sync_model)

File ~/Repos/holoviz/jupyter_bokeh/jupyter_bokeh/widgets.py:94, in BokehModel.update_from_model(self, model)
     92 def update_from_model(self, model):
     93     self._model = model
---> 94     self.render_bundle = self._model_to_traits(model)
     95     self._document.on_change_dispatch_to(self)

File ~/Repos/holoviz/jupyter_bokeh/jupyter_bokeh/widgets.py:83, in BokehModel._model_to_traits(cls, model)
     81 if model.document is None:
     82     document = Document()
---> 83     document.add_root(model)
     84 (docs_json, [render_item]) = standalone_docs_json_and_render_items([model], suppress_callback_warning=True)
     85 render_bundle = dict(
     86     docs_json=docs_json,
     87     render_items=[render_item.to_json()],
     88     div=div_for_render_item(render_item),
     89 )

File ~/miniconda3/envs/holoviz/lib/python3.10/site-packages/bokeh/document/document.py:317, in Document.add_root(self, model, setter)
    314 if model in self._roots:
    315     return
--> 317 with self.models.freeze():
    318     self._roots.append(model)
    320 self.callbacks.trigger_on_change(RootAddedEvent(self, model, setter))

File ~/miniconda3/envs/holoviz/lib/python3.10/contextlib.py:142, in _GeneratorContextManager.__exit__(self, typ, value, traceback)
    140 if typ is None:
    141     try:
--> 142         next(self.gen)
    143     except StopIteration:
    144         return False

File ~/miniconda3/envs/holoviz/lib/python3.10/site-packages/bokeh/document/models.py:135, in DocumentModelManager.freeze(self)
    133 self._push_freeze()
    134 yield
--> 135 self._pop_freeze()

File ~/miniconda3/envs/holoviz/lib/python3.10/site-packages/bokeh/document/models.py:288, in DocumentModelManager._pop_freeze(self)
    286 self._freeze_count -= 1
    287 if self._freeze_count == 0:
--> 288     self.recompute()

File ~/miniconda3/envs/holoviz/lib/python3.10/site-packages/bokeh/document/models.py:235, in DocumentModelManager.recompute(self)
    232     md._detach_document()
    234 for ma in to_attach:
--> 235     ma._attach_document(document)
    236     self._new_models.add(ma)
    238 self._models = recomputed

File ~/miniconda3/envs/holoviz/lib/python3.10/site-packages/bokeh/model/model.py:575, in Model._attach_document(self, doc)
    572     return
    574 if self.document is not None:
--> 575     raise RuntimeError(f"Models must be owned by only a single document, {self!r} is already in a doc")
    577 doc.theme.apply_to_model(self)
    578 self.document = doc

RuntimeError: Models must be owned by only a single document, ImportedStyleSheet(id='p1001', ...) is already in a doc
```

**Comment by Hoxbro** [comment]
A way to fix this is cloning the stylesheets in the following line with `model.stylesheets = [x._clone() if isinstance(x, ImportedStyleSheet) else x for x in model.stylesheets]` (or `clone` in the next Bokeh dev release because of https://github.com/bokeh/bokeh/pull/12823)

https://github.com/holoviz/panel/blob/a7c4ee3716fb4cb193f8f275bf1cf22496c2e883/panel/io/notebook.py#L454-L455

**Comment by philippjfr** [comment]
Would be happy for you to skip that test as ipywidgets rendering needs a separate look anyway.

**Comment by Hoxbro** [comment]
They are already marked with `bokeh3_failing` decorator.

I could get the string example to work with the above change and https://github.com/bokeh/jupyter_bokeh/pull/178.

**Review by philippjfr — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
