### PR TITLE
Update Image.ipynb 02 with added explanation that it selects another, sp…

### PR DESCRIPTION
**Pull request by Coderambling**
…ecific image pane to display an image

New commit, with added text explaining that image is a "macro" pane that selects a more specific image pane to display an image. Includes links to the API and source code of the pane.

### CODE REVIEW

**Comment by Coderambling** [comment]
json.decoder.JSONDecodeError: Expecting value: line 51 column 4 (char 2407)
That line has the closing character "]" .

Sorry that didn't work. I updated the text using a Notebook, but I obviously did something wrong, or 
[Image_new_text.ipynb.zip](https://github.com/user-attachments/files/15753120/Image_new_text.ipynb.zip)
[Image_new_text.ipynb.zip](https://github.com/user-attachments/files/15753122/Image_new_text.ipynb.zip)
perhaps the spacing is different?

Updated Markdown text:

The ``Image`` pane embeds any known image format file in panel if provided a local path, or will link to a remote image if provided with a URL.

The Image pane functions as a sort of "macro" pane that selects one of the more specific image panes to display the image (whichever one first recognizes this particular image format).

Please refer to the [API](https://panel.holoviz.org/api/panel.pane.html#image-module) and [source code](https://github.com/holoviz/panel/blob/main/panel/pane/image.py).

The classmethod get_pane_type returns the pane_type that was selected.

I have attached the edited .ipynb file (which works when opened in a Noteboo),  as a .zip

Please consult the documentation of each specific pane (JPG, PNG, SVG, etc.) for the options that particular pane will support.

**Comment by philippjfr** [comment]
Yeah you have to be quite careful editing notebooks directly.

**Comment by philippjfr** [comment]
I think this was superseded by https://github.com/holoviz/panel/pull/7004/. Thanks for following up!

**Comment by Coderambling** [comment]
Yes got there in the end!

**Pull request closed without merging**
