### PR TITLE
Stub experiments

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Addresses https://github.com/holoviz/panel/issues/3085

So far this is an experiment to be able to automatically create stub (`.pyi`) files to provide information in modern editors and IDEs.

I would like to make some general functionality that can take any project with `param.Parameterized` classes and add `.pyi` stubs. Either directly to the project or to some alternative folder or package. What is best is to be determined.

But I would like to be able to point it the Panel code as well as all the project I have for work and the Panel extensions I'm maintaining. I would like other `param` users to be able to do the same.

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks for all your experiments here. Agree with all your points, here are my expectations for this:

1. Ideally the code to generate the stubs moves to Param
2. We will not check the .pyi files into the repo but generate them at build time and include them in the package.
3. Adding docstrings is **always** welcome and we should decide asap whether we should convert them to markdown

**Comment by MarcSkovMadsen** [comment]
Totally agree with your points. 

There are additional options 

I. Stubs can be distributed as a separate package?

II. The functionality could live in a separate repo/ for a while until tried and tested on a multitude of projects?

**Comment by MarcSkovMadsen** [comment]
Regarding markdown. I prefer Markdown. Can this be Myst flavored Markdown now default for Sphinx? It would support better Sphinx generated docs as Panel matures I hope.

**Comment by philippjfr** [comment]
Highly appreciate the attempt here and won't delete the branch so we can come back to it but the stubgen definitely shouldn't live in Panel and I've started experimenting with other approaches.

**Comment by MarcSkovMadsen** [comment]
Please note this branch contains code for converting all Parameter types used in Panel to type annotations. Also handles default values and Allow_None arguments.

**Pull request closed without merging**
