### PR TITLE
Golden template fixes

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
The below comments are based on running `python -m panel serve 'panel\tests\template\test_manual.py' --dev`.

material_template

**Must Fix**

- Align logo center vertically
- Don't wrap header title
- Make sure additional items added to the header (left, center, right) buttons don't overflow on the right.
- Disable removing the sidebar.
    - If a user removes that by mistake is such a bad user experience.
- Give the sidebar a little bit of gray background 
    - This will more clearly separate it from the main area and be consistent with the Vanilla Template.

**Maybe Fix**

- Fix the sidebar at 300px just as for the Vanilla Template. 
    - The reason being that "fixed" is the default `sizing_mode" in Panel and using `stretch_width` a lot makes your application slower because the Bokeh layout engine needs to do a lot of work.
- Set overflow-x on sidebar and main area
    - It's just nice to have as few scrollbars as possible + consistency with Vanilla Template.

I have not implemented anything yet. But If @philippjfr and/ or @nghenzi could provide some feedback on what I should do I will do it.

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
If you "open the sidebar in a new window" you get a new window without content. That option should be disabled.

image

**Comment by philippjfr** [comment]
Items (at least partially) fixed in #1661

- [x] Align logo center vertically
- [x] Don't wrap header title
- [x] Make sure additional items added to the header (left, center, right) buttons don't overflow on the right. (I hid the overflow, wasn't able to figure out why the HSpacer was misbehaving here)
- [x] Disable removing the sidebar.
- [x] If you "open the sidebar in a new window" you get a new window without content. That option should be disabled.

**Comment by MarcSkovMadsen** [comment]
I've 

```bash
$ git pull holoviz golden_fixes
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 19 (delta 11), reused 19 (delta 11), pack-reused 0
Unpacking objects: 100% (19/19), 4.95 KiB | 60.00 KiB/s, done.
From https://github.com/holoviz/panel
 * branch              golden_fixes -> FETCH_HEAD
 * [new branch]        golden_fixes -> holoviz/golden_fixes
Merge made by the 'recursive' strategy.
 panel/template/golden/golden.css  | 15 ++++++++++++++-
 panel/template/golden/golden.html | 10 +++++++---
 2 files changed, 21 insertions(+), 4 deletions(-)
(base) (.venv)
```

It still looks like

image

**Comment by MarcSkovMadsen** [comment]
FYI @philippjfr . I will try to fix now. Let you know outcome before I leave.

**Comment by MarcSkovMadsen** [comment]
@philippjfr . When I change the golden.css file and run the application it's using an old golden.css file. I've tried to "refresh" the browser without luck.

Do I need something special now to update the css now that it is "bundled"

image

**Comment by MarcSkovMadsen** [comment]
If I run `python setup.py develop` the `golden.css` updates. Do I really need to do that for every small change?

That is a slow develop-iteration cycle.

**Comment by MarcSkovMadsen** [comment]
I've done a lot of improvements. 

Please note that I've changed the font from `roboto` (which did not work because the resources are not loaded) to the same font as Vanilla Template. Please note that bokeh again overrides this font. And the Bokeh Theme does not use this font. 

I think a consistent font across most Templates and Bokeh Themes would be nice to have.

One thing I could not solve (ran out of energy :-)) was the overflow indicated.

Overall I'm happy about the improvements.

Please note the test file has had it name changed. Run it via `python -m panel serve 'panel\tests\template\test_manual.py' --dev`.

And its now possible to select a Template via the query parameters such that it is easier to compare templates visually.

- http://localhost:5006/test_manual?template=vanilla
- http://localhost:5006/test_manual?template=golden
- http://localhost:5006/test_manual?template=material

image

**Comment by MarcSkovMadsen** [comment]
Inheriting from `DefaultTheme` and `DarkTheme` solved the `.css` issue. Now I just need to find out if the Bokeh JSON THEME is applied or not. And if not how to get it applied.

image

**Comment by MarcSkovMadsen** [comment]
@philippjfr . I reopen because as far as I can see you the many improvements I've contributed are not in the current MASTER.

The current MASTER looks like below . So for example there are a lot of scrollbars that I had removed.

image

**Comment by MarcSkovMadsen** [comment]
This branch looks like. So no problems with header or scrollbars.

image

**Comment by MarcSkovMadsen** [comment]
@philippjfr . If it is possible I would also like to get this one in as then I would be able to showcase it a awesome-panel.org.

Please read why I reopened in the comment above. The problem is that you don't have the header and scrollbar fixes in the MASTER branch as far as I can see.

**Comment by philippjfr** [comment]
You haven't rebased this PR, so I ported the changes that I thought were uncontroversial and left the rest for later.

**Comment by philippjfr** [comment]
>Please read why I reopened in the comment above. The problem is that you don't have the header and scrollbar fixes in the MASTER branch as far as I can see.

Can you point to where they're missing? Because I explicitly did port those changes.

**Comment by philippjfr** [comment]
I think you just haven't updated your CSS by rerunning `python setup.py develop`:

Screen Shot 2020-10-22 at 12 02 35 PM

**Comment by philippjfr** [comment]
Seeing some other issues though, going to work up on more PR with CSS fixes but I'm closing this one because it's not mergeable so please suggest changes there.

**Pull request closed without merging**
