### PR TITLE
Adds Plotly styling gallery notebook

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Addresses #3033

- notebook: https://mybinder.org/v2/gh/holoviz/panel/plotly-styling?urlpath=lab/tree/examples/gallery/styles/PlotlyStyle.ipynb
- app: https://mybinder.org/v2/gh/holoviz/panel/plotly-styling?urlpath=panel/PlotlyStyle

## Promo Videos

https://user-images.githubusercontent.com/42288570/147269980-52f4f31e-d85b-4446-b55b-a3f88714c3fc.mp4

PlotlyStyle

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks for these PRs. I'd like to avoid merging 2 MB+ images into the repo and am open to suggestions. Would be happy to put them in an S3 bucket for you but if you have an alternative self-service solution I'd love to hear it.

**Comment by MarcSkovMadsen** [comment]
An S3 bucket and a description in the developer guide on how to contribute assets like these would be super helpful.

Personally I just put my assets in a separate GitHub repo.

**Comment by MarcSkovMadsen** [comment]
For now I will just reference this .gif. Please upload to s3 bucket @philippjfr . Thanks

PlotlyStyle (1)

**Comment by philippjfr** [comment]
Here's the link: https://assets.holoviews.org/panel/thumbnails/gallery/styles/plotly-styles.gif

Maybe I'll create a bucket specifically for Panel one of these days but not today.

**Pull request merged**
