### PR TITLE
ChartJS

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Implements https://github.com/holoviz/panel/issues/1517

I have for a while 

- been wanting to add support for  ChartJS to Panel.
- been wanting to make it easier for the community to contribute Custom Models to Panel.

Now @Hoxbro stated he would like to contribute ChartJS and asked for help to get started.

This PR contributes a ChartJS extension and a notebook for getting started contributing `Custom Models`.

## Need to Do

[] Extend this todo
[] Support Height responsiveness (width seems to work)
[] Notebook Reference Guide with Examples
[] Test Some Examples

## Nice to Do
[] Themes: Should they be supported by default via https://nagix.github.io/chartjs-plugin-colorschemes/
[] Consider Supporting Events like mouse hover and click
[] Consider how to support chartjs plugins if necessary. See [list](https://www.chartjs.org/docs/2.7.2/notes/extensions.html)
[] Get Panel added to Chart.js list of integrations. See [list](https://www.chartjs.org/docs/2.7.2/notes/extensions.html#integrations)
[] Python Wrapper: Consider supporting [PyChart.JS](https://pypi.org/project/pyChart.JS/) or just document how to use.

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
The notebook guide states that you should start out with a small, simple, working example. That is what has been contributed so far. A Custom Button.

chartjs-button

Next Step would be to refactor into something that can show a minimal ChartJS example with inspiration from the `ECharts` pane.

@Hoxbro . Checkout the Notebook in the PR and let me know if it makes sense. Thanks.

**Comment by MarcSkovMadsen** [comment]
#### Hello ChartJS World!

image

**Comment by MarcSkovMadsen** [comment]
@Hoxbro. I will leave it here for now to let you play :-) I will pick it up later if needed. 

You can either continue the work I have done or try starting from scratch in another branch and let you guide by the notebook included in this PR.

https://user-images.githubusercontent.com/42288570/111076107-441f1200-84eb-11eb-9afa-d771f5c0b186.mp4

**Comment by MarcSkovMadsen** [comment]
FYI. @philippjfr and @Hoxbro 

I've moved the Custom Models guide to this PR https://github.com/holoviz/panel/pull/2084

**Comment by philippjfr** [comment]
@MarcSkovMadsen What's your feeling about this one? Is ChartJS worth supporting?

**Comment by MarcSkovMadsen** [comment]
Not compared to lots of other plotting libraries. For charts i would get echarts events and interactive matplotlib supported. Probably also more Plotly bugs fixed. Then look to apex charts if we want to support an Enterprise level plotting library. Probably getting panel-vegafusion merged would also be higher priority. And docs for using HoloViews efficiently with Panel. There are lots of things you know that the community probably does not know.

**Pull request closed without merging**
