### PR TITLE
Style fixes for Card and Accordion [doc-build]

### PR DESCRIPTION
**Pull request by philippjfr**
You can see the current builds here:

https://pyviz-dev.github.io/panel/reference/layouts/Accordion.html
https://pyviz-dev.github.io/panel/reference/layouts/Card.html

@MarcSkovMadsen @jbednar Further styling suggestions would be very welcome. Some questions I have:

* Should Card really have rounded corners? We use them elsewhere but I'm starting to think it looks cleaner without
* Should the Header title font be smaller by default?

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Hi @philippjfr 

I just love the accordion. 

- I also thinks it looks nice in the notebook without the rounded corners
- An i just thought wow that clicking the header toggles it open and closed.

There is alternative inspiration for accordions (material expansions) here https://material.angular.io/components/expansion/overview.

**Comment by MarcSkovMadsen** [comment]
Regarding the according notebook. Could you make one of the example full width?

Just to illustrate that its possible and how to do it.

**Comment by MarcSkovMadsen** [comment]
Regarding the Card. Three comments

#### Double border below.

I actually cannot say if it is good or bad. But it is different than bootstrap.

image

#### `button_color`

I guess it (should?) affect the color of the header text as well. Should it be called `header_color`?

image

#### Divider

Could you throw in a divider in the last example? 

Just to show case you can seperate things in the card and that lays out nicely.

image

**Comment by philippjfr** [comment]
>I actually cannot say if it is good or bad. But it is different than bootstrap.

Fixed.

>I guess it (should?) affect the color of the header text as well. Should it be called header_color?

Fixed.

>Could you throw in a divider in the last example?

Done.

**Comment by MarcSkovMadsen** [comment]
hmm. Something must have gone wrong. The accordion example looks like

image

**Comment by philippjfr** [comment]
The daily doc build is built from master.

**Comment by jbednar** [comment]
It would be nice if the docs for Card showed some cards side by side; right now it's not clear that it's expected you'd use them that way.

**Comment by philippjfr** [comment]
>It would be nice if the docs for Card showed some cards side by side; right now it's not clear that it's expected you'd use them that way.

True and nested cards.

**Comment by MarcSkovMadsen** [comment]
And maybe throw in an example with some text and an image. This is something that is a normal use case for cards as well.

**Comment by MarcSkovMadsen** [comment]
Maybe an image like.

image

:-)

**Comment by philippjfr** [comment]
😄 

This is the current status of cards in the material template btw:

Screen Shot 2020-04-14 at 7 02 45 PM

**Comment by jbednar** [comment]
Nice!

**Pull request merged**
