### PR TITLE
Update charts example

### PR DESCRIPTION
**Pull request by kcpevey**
Adds `pyechart` example discussed in [this issue](https://github.com/holoviz/panel/issues/1874). 

I suspect this will also need `pyechart` added to the ci environment but I'm not sure where exactly to do that.

### CODE REVIEW

**Comment by philippjfr** [comment]
Thanks @kcpevey!

**Comment by kcpevey** [comment]
I wasn't sure if the optional dep should be added to setup.py or not. Thanks for taking it the rest of the way!

**Comment by philippjfr** [comment]
Thanks for contributing! I tried, didn't work since setup.py is used as the source of the conda env and it's not yet available on conda. So manual pip install is all we could do for now.

**Comment by kcpevey** [comment]
ah ok. That makes sense!

**Pull request merged**
