### PR TITLE
Fixes for Column invisible scroll_button taking space

### PR DESCRIPTION
**Pull request by philippjfr**
Columns showed a bogus scrollbar due to the scroll button.

### CODE REVIEW

**Comment by ahuang11** [comment]
I think the arrow is now at the top right rather than bottom right with this change.
image

**Comment by ahuang11** [comment]
I think re-setting `top: calc(100% - 38px);` fixes it.

**Comment by philippjfr** [comment]
Cannot reproduce that, still at the bottom right for me.

**Comment by ahuang11** [comment]
Weird, I was using Google Chrome. I also deleted my cache.

**Pull request merged**
