### PR TITLE
Improved Home App

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Addresses #3043, #3042, #2980

Improves the home app by making it more responsive, showing relevant gifs of Panel in the SlideShow and making the code runnable.

https://user-images.githubusercontent.com/42288570/147473199-129c9938-2b6d-4ab0-91fb-d8c6bd5f6083.mp4

You will have to finalize and test @philippjfr as I don't know how to put it on the home page and whether it needs special considerations.

Feel free to copy or create your own Gifs for Panel. My suggestion would be to crowd source gifs from our community longer term. That would be awesome. Alternatively the slideshow could be turned into something showing a png or gif of each reference and gallery example with a link to the notebook.

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
I will improve it with some text and better gifs. I'm working on it

panel-promo

**Comment by MarcSkovMadsen** [comment]
Improved. I plan to leave it here until I get a review and some feedback.

https://user-images.githubusercontent.com/42288570/147571194-9ba19a52-9fe5-4c90-86c4-249310eeacea.mp4

**Comment by philippjfr** [comment]
Thanks @MarcSkovMadsen, I plan to review when I'm back from vacation on the 2nd. Guten Rutsch as we Germans say!

**Comment by philippjfr** [comment]
This is great thank you, however I'm not entirely comfortable pointing the repository to a CSV and set of images that isn't under the HoloViz communities control. Will download those images and put them somewhere I can control, although I really would like some GitHub based repo with assets like this.

**Comment by MarcSkovMadsen** [comment]
You should put Them somewhere under panels control.

If one day there could be an official way to contribute assets it would be great.

**Comment by jbednar** [comment]
Very nice! The UI for the slideshow feels a bit odd; usually that would be a player app rather than a slider. To me a slider is really for things that have a well defined order, whereas a player app evokes "slideshow" to me.  I guess that with a player you'd need a separate div that has a title, though, because those titles are helpful.

**Comment by philippjfr** [comment]
Sorry I never got back to this. I'm very happy to see the responsiveness changes but tbh I'm not excited about  adding the imports and extensions to the code. Users know you need to run imports and will learn about the extension so it doesn't add anything and distracts from the actual important parts. I'll reopen a new PR to improve the responsiveness.

**Pull request closed without merging**
