### PR TITLE
[WIP] use idom.config to set dist dir

### PR DESCRIPTION
**Pull request by rmorshea**
See https://github.com/idom-team/idom/pull/320 for more context on this change.

Closes: #2058

### CODE REVIEW

**Comment by rmorshea** [comment]
Marking as WIP for right now. I'm still straightening some stuff out at the moment in `idom`

**Comment by philippjfr** [comment]
Thanks @rmorshea!

**Comment by rmorshea** [comment]
@philippjfr there's actually some more follow up work. Will create another PR for that though.

**Comment by philippjfr** [comment]
Thanks again @rmorshea and sorry for the premature merge.

**Comment by rmorshea** [comment]
No worries

**Pull request merged**
