### PR TITLE
Add ScrollLog with TypeScript

### PR DESCRIPTION
**Pull request by ahuang11**
Refactors https://github.com/holoviz/panel/pull/5212 so it's implemented as a Typescript subclass of the Bokeh Column based on the this suggestion https://github.com/holoviz/panel/pull/5212#issuecomment-1621938112

I understand that Marc would like to add "actions" like AutoScroll FullScreen, Sort, etc. to a Column, but first I'd like to figure out how to translate the ReactHTML into Typescript as a draft first.

I modeled this after `pn.Card`, but I'm missing something related to registration:
```
Bokeh items: Error: could not resolve type 'panel.models.layout.ScrollLog', which could be due to a widget or a custom model not being registered before first usage
```

Even after running `python setup.py develop` and `panel build panel`

### CODE REVIEW

**Comment by Hoxbro** [comment]
I think you are missing adding it to index.ts

A PR for inspiration could be https://github.com/holoviz/panel/pull/4909 as it is very limited in scope and implements a new model.

**Comment by ahuang11** [comment]
Thanks for sharing that; I'll definitely use that as reference.

I added index.ts, but it's still showing the same thing; maybe an error in my Typescript.

**Comment by philippjfr** [comment]
Also to be fully clear the suggestion was to swap out the model that renders `Column` and then add an option to add the scroll features, so we don't add yet another layout.

**Comment by ahuang11** [comment]
I still can't seem to register it to get a testable version :(

```python
Error rendering Bokeh items: Error: could not resolve type 'panel.models.layout.ScrollLog', which could be due to a widget or a custom model not being registered before first usage
    at p.error (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:4951)
    at p._resolve_type (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:5059)
    at p._decode_object_ref (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:4782)
    at p._decode (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:1779)
    at bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:2249
    at f (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:178:450)
    at p._decode_plain_array (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:2237)
    at p._decode (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:928)
    at bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:614
    at p.decode (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:211:730)
```

**Comment by philippjfr** [comment]
Did you try shift-reload? Are you testing in a notebook?

**Comment by ahuang11** [comment]
Oh shift-reload changed the error. Okay, so I think I now can test.
```python
Error rendering Bokeh items: TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at r.connect_signals (panel.min.js?v=3d8aca08eab1e0268df3670e2d168569f81cfcdfaac4320304acbd95653e5732:143:477)
    at t.build_view (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:224:342)
    at async bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:218:236
    at async f (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:218:198)
    at async t.add_document_standalone (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:218:459)
    at async g (bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:163:804)
```

**Comment by ahuang11** [comment]
Woohoo got it to work. Will try to generalize it to a new `PanelColumn` model next

https://github.com/holoviz/panel/assets/15331990/db4cecba-5915-4c58-8b22-975d1d576bc4

**Comment by ahuang11** [comment]
Here's my attempt to extend BkColumn.
https://github.com/holoviz/panel/compare/column_replacement?expand=1

I think there's an issue with name conflict because I get this warning/error in VSCode
```
File name '/Users/ahuang/repos/panel/panel/node_modules/@bokeh/bokehjs/build/js/lib/models/layouts/Column.d.ts' differs from already included file name '/Users/ahuang/repos/panel/panel/node_modules/@bokeh/bokehjs/build/js/lib/models/layouts/column.d.ts' only in casing.
  The file is in the program because:
    Imported via "./column" from file '/Users/ahuang/repos/panel/panel/node_modules/@bokeh/bokehjs/build/js/lib/models/layouts/index.d.ts' with packageId '@bokeh/bokehjs/build/js/lib/models/layouts/column.d.ts@3.2.0'
    Imported via "@bokehjs/models/layouts/column" from file '/Users/ahuang/repos/panel/panel/models/card.ts' with packageId '@bokeh/bokehjs/build/js/lib/models/layouts/column.d.ts@3.2.0'
    Imported via "@bokehjs/models/layouts/Column" from file '/Users/ahuang/repos/panel/panel/models/column.ts' with packageId '@bokeh/bokehjs/build/js/lib/models/layouts/Column.d.ts@3.2.0'ts(1149)
index.d.ts(1, 24): File is included via import here.
card.ts(1, 34): File is included via import here.
module "/Users/ahuang/repos/panel/panel/node_modules/@bokeh/bokehjs/build/js/lib/models/layouts/column"
No quick fixes available
```

**Comment by philippjfr** [comment]
Can you push your changes?

**Comment by ahuang11** [comment]
Yep; it's on this branch: 
`column_replacement`
https://github.com/holoviz/panel/pull/5245

**Comment by ahuang11** [comment]
Closed in favor of https://github.com/holoviz/panel/pull/5245

**Pull request closed without merging**
