### PR TITLE
Ensure bokeh correctly detects whether HTML/Markdown contains latex

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes https://github.com/holoviz/panel/issues/3429

### CODE REVIEW

**Comment by philippjfr** [comment]
@MarcSkovMadsen So the fast templates have this bit of CSS in them:

```python
  :not(:defined) {
    visibility: hidden;
  }
```

This seems to hide the `mjx-container` tags that MathJax adds to the page to render the LaTeX output. Do you recall why this rule had to be added?

**Comment by MarcSkovMadsen** [comment]
Yes. The fast documentation specifiks they should be added to avoid having the page look write indtil web components have been defined.

**Comment by philippjfr** [comment]
So it should be removed after the page is fully rendered?

**Comment by philippjfr** [comment]
Will merge and fix the fast template issue separately.

**Pull request merged**
