### PR TITLE
Add server video stream tutorial

### LINKED ISSUE #6724: Set up Manual Threading how-to guide is highly problematic
I've been looking at the [Set up Manual Threading](https://panel.holoviz.org/how_to/concurrency/manual_threading.html) multiple times and I think it will cause more harm the good.

- It lacks the `import panel as pn` text.
- It does not explain how to stop the thread when the session is ended. Thus more and more threads will be created.
- It does not explain how to stop the thread when the app is autoreloaded.
- Even though there is some attempt at explaining why use of `c = threading.Condition()` is nescessary I'm not sure the explanation is True. My understanding the Condition enables another thread to wait until a condition. And this is not what we do here. See https://docs.python.org/3/library/threading.html#condition-objects.
- I lack some comment about safety of updating Panel components from separate threads. Is that safe? Why?

Maybe use of session life cycle hooks are solution? https://panel.holoviz.org/how_to/callbacks/session.html.

---

Furthermore the guide only explains how to use manual thread in main `app.py` file that is not shared between sessions. I would also like to see an explanation of using a single shared thread in external module. As in https://github.com/holoviz/panel/issues/6723. I think here concerns about performance comes in. Should this thread be pushing updates to all sessions that `.depends` on the threads updates? Or should each individual session be running a periodic callback to check for updates? What is most safe and performant?

---

[x] Yes. I'm willing to contribute a PR updating the guide. But I need some guidance and more understanding to be able to do it.

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Adds a `ServerVideoStream` tutorial motivated by questions on discourse. For example in https://discourse.holoviz.org/t/best-practice-for-displaying-high-resolution-camera-images-captured-on-server/4285 and  https://discourse.holoviz.org/t/streaming-local-video/6929.

As this tutorial uses *manual threading* I would also like to fix #6724.

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
This PR can be reviewed. I can work for users.

But it would be much stronger if https://github.com/holoviz/panel/issues/6724 was first addressed and applied to this PR.

**Review by philippjfr — APPROVED** [review]

**Comment by philippjfr** [comment]
>this PR updated accordingly.

I'm not sure what you mean by that, are you saying that this guide currently does not use best practices?

**Comment by MarcSkovMadsen** [comment]
> > this PR updated accordingly.
> 
> I'm not sure what you mean by that, are you saying that this guide currently does not use best practices?

No i'm saying I don't know what best practice is. It would be great to get that established in the how-to guide and then apply here.

**Comment by philippjfr** [comment]
Got you, thanks!

**Comment by MarcSkovMadsen** [comment]
> Got you, thanks!

This use case is not described in the how-to guide. It explains how to setup a worker thread for each session in a served file.

This use case sets up a shared worker thread in a separate module. All sessions listen/ subscribe/ take the same frame. Currently shared via a parameter on a Parameterized class.

For example right now each time the app is autoreloaded a new worker thread is started and the old not stopped. Your comment in other issue about using `on_session_destroyed` does not apply here as that only works for sessions.

**Comment by philippjfr** [comment]
>For example right now each time the app is autoreloaded a new worker thread is started and the old not stopped. Your comment in other issue about using on_session_destroyed does not apply here as that only works for sessions.

I don't follow, autoreload creates new sessions.

**Comment by philippjfr** [comment]
Ah sorry, I guess I'm following you. You're saying this guide demonstrates the shared worker thread and you want each session to subscribe and unsubscribe. That still should still be done via `on_session_destroyed` handlers though, so I'm not entirely following this point "on_session_destroyed does not apply here as that only works for sessions".

**Comment by MarcSkovMadsen** [comment]
But i dont want that friction. I just want to panel serve as normal such that the component can be importen and used as other component even though its shared.

**Comment by philippjfr** [comment]
You can use the cache to to share the thread instance. I appreciate the pursuit of "reducing friction" but you can't reduce all friction for every conceivable complex use case.

**Comment by philippjfr** [comment]
>The session is not the problem. The problem is that the external module is reimported on autoreload - thus starting another thread. 

Got it, that makes sense. I guess another reason to use the cache.

**Comment by MarcSkovMadsen** [comment]
The cache is a good idea. Did not Think about that.

**Review by philippjfr — APPROVED** [review]

**Pull request merged**
