### PR TITLE
Add support for converting Panel apps to pyscript/pyodide

### PR DESCRIPTION
**Pull request by philippjfr**
Implements conversion of a standard Panel app (in a .py or .ipynb file) to a standalone PyScript/Pyodide application.

Depends on https://github.com/pyscript/pyscript/pull/130

- [x] Add pure pyodide support
- [x] Add pyodide in a web worker support 
- [x] Add CLI

### Example

```bash
panel convert ./examples/gallery/simple/random_number_generator.ipynb --to pyscript
```

Output:

panel_auto

### CODE REVIEW

**Comment by philippjfr** [comment]
Note that this PR will not actually work until there is a dev release out containing the code in this PR because pyodide has to be able to load this from PyPI.

**Comment by philippjfr** [comment]
Just ran through all gallery example after converting them to apps, here's the ones that are working and those that are not

# Working

- action button
- altair_choropleth
- bokeh_property_editor
- deck_gl_json_editor
- deckgl_game_of_life
- distribution_tabs
- download_upload_csv
- dynamic_plot_layout
- dynamic_timeseries_image_analysis
- dynamic_tabs
- dynamic_ui
- dynamic_widget_values
- file_download_examples
- Folium
- hardware_automation
- holoviews_glyph_link
- iris_kmeans
- param_subobjects
- plot_with_columns
- plotly_link
- precedence
- random_number_generator
- reactive_plots
- save_filtered_df
- streaming_bokeh
- streaming_indicator
- streaming_perspective
- streaming_tabulator
- temperature_distribution
- vega_heatmap_link

# To fix in Panel

## Loading spinner not working (JS does not seem to find the element)

- loading_indicator
- loading_spinner

## render_items out-of-range error (probably down to the way the examples are written)

- MatplotlibStyle
- PlotlyStyle
- SeabornStyle
- VegaAltairStyle

## Import errors

- plotly_link (plotly not found)

## Location not synced with widgets on load

- sync_location

## Various

- CanvasDraw (canvas not defined in JS)
- color_speech_recognition (invalid grammar supplied to model in JS)
- material_template (Indentation errors in pyscript probably due to syntax that HTML is unhappy about being inside a tag)

# Pyodide related issues

## Bokeh Sampledata not downloadable

- reactive_tables
- stocks_altair
- stocks_hvplot
- stocks_matplotlib

# Library related 

- clifford_interact (no numba)
- deck_gl_global_power_plants (pydeck imports tornado)
- GraphViz (graphviz not installable)

# Network access

- defer_data_load
- LeafletHeatMap

**Comment by jbednar** [comment]
Not bad!!!

**Comment by MarcSkovMadsen** [comment]
Should libraries like Pandas, Xarray etc not start supporting pyiode environments when they load data from urls? That would make it much easier to convert seamlessly.

**Comment by philippjfr** [comment]
They should but they never will because the browser will simply not allow it. All APIs for fetching (binary) data in the browser are asynchronous so there's no straightforward way to support synchronous APIs like pd.read_parquet. That said, pd.read_csv can be supported and that's already a great start. I've been trying to get the creator of fsspec (which underlies remote file access in pandas) to implement this in some form.

**Comment by philippjfr** [comment]
Will probably merge quite soon and cut a dev release. Documentation and further polish to follow.

**Pull request merged**
