### PR TITLE
Fix: Fast Template to use Fast Theme instead of Vanilla Theme

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Fixes https://github.com/holoviz/panel/issues/2040

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Would it be possible to get this one in @philippjfr . It's important as the whole look and feel of the Fast Templates with HoloViews plots is different.

**Comment by MarcSkovMadsen** [comment]
After reviewing this I can see my first fix only fixed problems on the surface. I got it to use the FastDarkTheme. But I should actually get it to use the FastListDarkTheme and FastGridDarkTheme respectively.

I've now refactored the tests and implementation. I believe I have solved it.

But I still have problems getting the panel `dev` environment running. So I cannot thoroughly test it. Sorry.

**Comment by MarcSkovMadsen** [comment]
@philippjfr . The two failing tests I simply don't understand. I think it has something todo with how templates and themes are related. I have tried to understand that for a long time but not yet been able to. I've fix the problem but as I simply don't understand the flow its not possible for me.

I can see though that where it fails if the theme is instantiated `()` there is no error. But the theme parameter is a class and not an instance. 

image

I have tried to understand what a property descriptor is without luck.

`ValueError: Parameter 'theme' value must be an instance of (Theme, str), not '<property object at 0x7fb96f5fc5f0>'`

**Can you help?**

**Comment by xavArtley** [comment]
I think you make a wrong usage of the property decorator:
If you don't instantiate your class you are just returning the declaration of your property
image

**Comment by philippjfr** [comment]
This is not how themes work. They get resolved internally to the actual theme class that will be applied but the user and the parameter hold the base class.

**Comment by philippjfr** [comment]
Anyway I'll check into why the bokeh theme isn't correctly applied.

**Comment by philippjfr** [comment]
Basically a user should never see or know about the fact that there are template specific themes. They import and provide the theme base class and in the background it resolves it to the concrete theme object for that template. Closing this PR and investigating.

**Pull request closed without merging**
