### PR TITLE
Improve BasicTemplate type hints

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Fixes issues like below

image

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
I don't know how you got type hints in using `| ` @philippjfr ? These will fail when running on Python < 3.10 I believe.

image

**Comment by philippjfr** [comment]
The union operator is compatible with `from __future__ import annotations` in older versions of python. You just can't express type aliases that way.

**Comment by MarcSkovMadsen** [comment]
> Thanks. Does it mean I should refactor this one to annotate using `Path | str | List[Path| str]` instead of `Union[Path, str, List[Union[Path, str]]` and add `from __future__ import annotations` @philippjfr ?

I can see from https://github.com/holoviz/panel/pull/3560#discussion_r882431205 that it does. I will update.

**Comment by philippjfr** [comment]
Perfect, thanks!

**Comment by philippjfr** [comment]
Finished typing `template/base.py` in this PR.

**Pull request merged**
