### PR TITLE
Hide ChatMessage footer until hover

### PR DESCRIPTION
**Pull request by ahuang11**
I wanted to do something like this:
```css
.chat-message:hover .reaction-icons,
.chat-message:hover .footer,
.chat-message:hover .header {
  opacity: 1;
}

.reaction-icons,
.footer,
.header {
  opacity: 0;
  transition: opacity 0.2s;
}
```

To hide all elements until hover over the chat message

https://github.com/holoviz/panel/assets/15331990/3aadfede-b6ae-4031-8e24-4c898157f3fe

But shadow root only allows me to target one at a time I think:

https://github.com/holoviz/panel/assets/15331990/efdc09e1-b514-4f6a-ba29-d228fab8fee1

### CODE REVIEW

**Comment by philippjfr** [comment]
>But shadow root only allows me to target one at a time I think:

I'm quite unsure what you mean.

**Comment by ahuang11** [comment]
I can't do this
```
.chat-message:hover .reaction-icons,
.chat-message:hover .footer,
.chat-message:hover .header {
  opacity: 1;
}

.reaction-icons,
.footer,
.header {
  opacity: 0;
  transition: opacity 0.2s;
}
``` because reaction icons are nested in shadow root

**Comment by philippjfr** [comment]
Wouldn't that have to be?

```
:host(.chat-message:hover) .reaction-icons,
:host(.chat-message:hover) .footer,
:host(.chat-message:hover) .header {
  opacity: 1;
}
```

**Comment by ahuang11** [comment]
I think I tried that too and it didn't work

**Comment by philippjfr** [comment]
I see, the problem with that the DOM is nested pretty deep and it's not quite clear to me how to write a selector that traverses nested shadow hosts.

**Comment by ahuang11** [comment]
Don't think this is possible with shadow doms; closing for now.

**Pull request closed without merging**
