### PR TITLE
Adapt tests to Param 2 changes

### PR DESCRIPTION
**Pull request by maximlt**
Adapting tests to:

- updated validation error messages
- updated signature

`panel_extension._apply_signatures` can't yet be removed as Param only updates the signature of a Parameterized class when its `__init__` signature hasn't changed at all compared to `Parameterized.__init__`, while `_apply_signatures` can handle updating Panel objects (e.g. with `def __init__(self, object, ...)`).

### CODE REVIEW

**Comment by philippjfr** [comment]
Tests seem quite unhappy!

**Comment by philippjfr** [comment]
Also can you replace usage of `._param_watchers`?

**Comment by maximlt** [comment]
> Also can you replace usage of `._param_watchers`?

This was already done in https://github.com/holoviz/panel/pull/5350 :)

**Comment by philippjfr** [comment]
> This was already done in #5350 :)

Not quite, `param.config` L388 still has a usage of it.

**Pull request merged**
