### PR TITLE
Model viewer example

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Moving ModelViewer example from https://github.com/holoviz/panel/pull/1122 into this PR.

Improving the example.

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
model_viewer_small

**Comment by MarcSkovMadsen** [comment]
@xavArtley . FYI.

If you have good ideas for improving this example let me know.

**Comment by MarcSkovMadsen** [comment]
Changed to new suggested template and beautified the example

image

**Comment by philippjfr** [comment]
Closing for now as we discussed. Hope we can re-add it in some form later.

**Comment by MarcSkovMadsen** [comment]
Please don't delete for now. Still need the notebook as a example of a WebComponent implementation.

**Pull request closed without merging**
