### PR TITLE
Comment out template output in best practices docs

### PR DESCRIPTION
**Pull request by ahuang11**
Comment out templates in best practices; I suspect it's causing scrolling issues.

### CODE REVIEW

**Comment by ahuang11** [comment]
It's able to properly scroll now

image

**Comment by hoxbro** [comment]
Couldn't you just change the pyodide marker to python?

**Comment by ahuang11** [comment]
Not sure I follow. Can you elaborate?

**Comment by hoxbro** [comment]
Change 

````

```{pyodide}

````

To

````

```python

````

**Review by philippjfr — APPROVED** [review]

**Pull request merged**
