### PR TITLE
Example of using Folium in Panel - Notebook for Gallery

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Demonstrates the use of [`Folium`](https://python-visualization.github.io/folium/) in Panel.

This notebook was created as a response to the [Panel and Folium do they mix](https://discourse.holoviz.org/t/panel-and-folium-do-they-mix/342) question on [Discourse](https://discourse.holoviz.org/).

panel_folium_example

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
See also https://twitter.com/MarcSkovMadsen/status/1242896463635591168

Share if you like.

**Comment by philippjfr** [comment]
Thanks, nice how easy this is. Could you either add folium to the test dependencies in setup.py or put a regex to skip testing the notebook at the end of the tox.ini?

**Comment by MarcSkovMadsen** [comment]
I've added Folium to the test requirements @philippjfr 

image

**Comment by MarcSkovMadsen** [comment]
I've shared a tweet. Feel free to share if you like https://twitter.com/MarcSkovMadsen/status/1243405883175911426?s=20

voltage_example

**Comment by philippjfr** [comment]
>FileNotFoundError: [Errno 2] File sample_data.csv does not exist: 'sample_data.csv'

Seems to be erroring, I also haven't quite decided how to handle sample data files in Panel yet.

**Comment by MarcSkovMadsen** [comment]
The idea is that the user generates the sample data by clicking the save button.

Will look for a workaround

**Pull request merged**
