### PR TITLE
Add ChatBox usage examples, simplify DEVEX and improve UX.

### LINKED ISSUE #5277: Make ChatBox usage easy
From experience the ChatBox is currently not as easy to use as it should be.

I believe there is functionality and documentation that should be added, changed or updated. This can be done in many ways.

I believe the best way to agree on solutions is to document how to easily use the ChatBox for the most common use cases.

Please add documentation and tests for the most common use cases. Improve the `ChatBox` based on these use cases.

## Use Cases

I think we can find use cases by looking at

- Streamlit
- Gradio
- Langchain
- Guidance

And similar frameworks.

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Closes #5277 

- [ ] Add test examples
  - [x] Atomic Use Cases
  - [ ] Gradio
    - [x] HighLevel `ChatBoxInterface`: [reference](https://www.gradio.app/docs/chatinterface), [tutorial](https://www.gradio.app/guides/creating-a-chatbot-fast)
    - [ ] Low Level `Chatbot`: [reference](https://www.gradio.app/docs/chatbot), [tutorial](https://www.gradio.app/guides/creating-a-custom-chatbot-with-blocks)
      - [x] ClearButton
      - [x] RetryButton
      - [x] UndoButton
      - [ ] file links (local or url)
        - [ ] audio, video and image links are displayed
        - [ ] other file links are turned into download links
- [ ] Review: Agree on best practice for implementing examples and needed functionality
- [ ] Improve needed functionality of Chatbox
  - [ ] Refactor into ChatBox and ChatInterface
  - [ ] Agree on message format
- [ ] Add and update component guide(s)
- [ ] Add tutorials

## Missing Functionality

- Clear Button to clear the chatbot history and the textinput

### CODE REVIEW

**Comment by ahuang11** [comment]
Thanks for adding this!

With the temporary message class, I think it can be abstracted and generalized to a temporary pane / placeholder.

**Comment by philippjfr** [comment]
As an aside I'd like to implement a `TextFragment` component or similar that allows efficiently streaming text without having to send the entire string every time it is updated.

**Comment by MarcSkovMadsen** [comment]
That is great and needed. How will you handle that it should convert markdown as it streams? And maybe even do other types of parsing on the fly?

**Comment by MarcSkovMadsen** [comment]
> Thanks for adding this!
> 
> With the temporary message class, I think it can be abstracted and generalized to a temporary pane / placeholder.

Could you tell more about this idea. I'm not sure I understand. The `ChatResponse` as its now called is a ContextManager.

**Comment by MarcSkovMadsen** [comment]
From a User Experience perspective `pn.Placeholder` could be nice.

But would we like to extra functionality or just guide users to replace elements in existing layouts via indexing?

For example

```python
layout[2]=pn.widget.ChatRow(...)
```

**Comment by MarcSkovMadsen** [comment]
Closing this one as the "tests" done so far are fully covered by @ahuang11 work in https://github.com/holoviz/panel/pull/5333 except having a context manager to temporarily 1. disable the `ChatFeed` and 2. indicator progress. The `callback` on the `ChatFeed` covers many of the use cases of the context manager.

I will add an example of creating a context manager to the reference notebook for the `ChatFeed`.

**Pull request closed without merging**
