### PR TITLE
Fix Fast Tabulator issues

### LINKED ISSUE #4351: Fast Template + Tabulator w. fast theme styling issues
I'm on the current master branch of Panel (+0.14.2).

While working on contributing #4350 I've discovered some styling issues:

- Links (`<a>`) are not styled
- If using `list` formatter the dropdown list is displayed in the lower, left corner

```python
import panel as pn
import pandas as pd
from io import StringIO
pn.extension("tabulator", template="fast")

csv = """\
ticker,info,action
AAPL,<a href='https://finance.yahoo.com/quote/AAPL' target='_blank'>LINK</a>,buy
MSFT,<a href='https://finance.yahoo.com/quote/MSFT' target='_blank'>LINK</a>,sell
AMZN,<a href='https://finance.yahoo.com/quote/AMZN' target='_blank'>LINK</a>,hold"""

df = pd.read_csv(StringIO(csv))

editors = {
    "ticker": None,
    "action": {"type": "list", "values": {"buy": "buy", "sell": "sell", "hold": "hold"}},
    "info": None,
}

formatters = {
    "info": {"type": "html", "field": "html"},
}

component= pn.widgets.Tabulator(df, editors=editors, formatters=formatters, theme="fast").servable()
```

You can see the issues in the video below.

https://user-images.githubusercontent.com/42288570/215283423-ff36c87a-909f-4dc4-af38-a9115f942c2b.mp4

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Closes #4351

# Todo

- Add CSS in python script below to some ` tabulator_fast...csv` file. @philippjfr said I should wait until Panel 1.0 is merged into main branch.

## Python

```python
import panel as pn
import pandas as pd
from io import StringIO

CSS = """
.main .pnx-tabulator a {color: var(--accent-foreground-rest);text-decoration:none;}
.main .pnx-tabulator .tabulator-row:hover a {color: var(--neutral-fill-stealth-hover);}
.main .pnx-tabulator .tabulator-row a:hover {color: inherit;}
.main .pnx-tabulator .tabulator-row.tabulator-selected a {color: var(--accent-foreground-cut-rest);}
.tabulator-popup-container{position:absolute;display:inline-block;box-sizing:border-box;background:var(--neutral-fill-hover);border:1px solid var(--neutral-fill-rest);box-shadow:0 0 5px 0 rgba(0,0,0,.2);font-size:14px;overflow-y:auto;-webkit-overflow-scrolling:touch;z-index:10000}.tabulator-popup{padding:5px;border-radius:3px}.tabulator-tooltip{max-width:Min(500px,100%);padding:3px 5px;border-radius:2px;box-shadow:none;font-size:12px;pointer-events:none}.tabulator-menu .tabulator-menu-item{position:relative;box-sizing:border-box;padding:5px 10px;user-select:none}.tabulator-menu .tabulator-menu-item.tabulator-menu-item-disabled{opacity:.5}
.tabulator-edit-list{max-height:200px;font-size:14px;overflow-y:auto;-webkit-overflow-scrolling:touch}.tabulator-edit-list .tabulator-edit-list-item{padding:4px;color:inherit;outline:none}.tabulator-edit-list .tabulator-edit-list-item.active{color:inherit;background:var(--neutral-fill-active)}.tabulator-edit-list .tabulator-edit-list-item.active.focused{outline:1px solid hsla(0,0%,40%,.5)}.tabulator-edit-list .tabulator-edit-list-item.focused{outline:1px solid var(--neutral-fill-active)}.tabulator-edit-list .tabulator-edit-list-item:hover{cursor:pointer;color:inherit;background:var(--neutral-fill-active)}.tabulator-edit-list .tabulator-edit-list-placeholder{padding:4px;color:inherit;text-align:center}.tabulator-edit-list .tabulator-edit-list-group{border-bottom:1px solid var(--neutral-fill-rest);padding:6px 4px 4px;color:inherit;font-weight:700}.tabulator-edit-list .tabulator-edit-list-group.tabulator-edit-list-group-level-2,.tabulator-edit-list .tabulator-edit-list-item.tabulator-edit-list-group-level-2{padding-left:12px}.tabulator-edit-list .tabulator-edit-list-group.tabulator-edit-list-group-level-3,.tabulator-edit-list .tabulator-edit-list-item.tabulator-edit-list-group-level-3{padding-left:20px}.tabulator-edit-list .tabulator-edit-list-group.tabulator-edit-list-group-level-4,.tabulator-edit-list .tabulator-edit-list-item.tabulator-edit-list-group-level-4{padding-left:28px}.tabulator-edit-list .tabulator-edit-list-group.tabulator-edit-list-group-level-5,.tabulator-edit-list .tabulator-edit-list-item.tabulator-edit-list-group-level-5{padding-left:36px}
"""

pn.extension("tabulator", template="fast", raw_css=[CSS])

csv = """\
ticker,info,action
AAPL,<a href='https://finance.yahoo.com/quote/AAPL' target='_blank'>LINK</a>,buy
MSFT,<a href='https://finance.yahoo.com/quote/MSFT' target='_blank'>LINK</a>,sell
AMZN,<a href='https://finance.yahoo.com/quote/AMZN' target='_blank'>LINK</a>,hold"""

df = pd.read_csv(StringIO(csv))

editors = {
    "ticker": None,
    "action": {"type": "list", "values": {"buy": "buy", "sell": "sell", "hold": "hold"}},
    "info": None,
}

formatters = {
    "info": {"type": "html", "field": "html"},
}

component= pn.widgets.Tabulator(df, editors=editors, formatters=formatters, theme="fast").servable()
```

https://user-images.githubusercontent.com/42288570/215288208-30ef3038-da4f-4670-b353-585f724b48ff.mp4

### CODE REVIEW

**Comment by philippjfr** [comment]
Yeah as I said, I basically can't merge this PR at all since this file doesn't even exist anymore on branch-1.0

**Comment by philippjfr** [comment]
Happy to actually apply these changes though.

**Comment by MarcSkovMadsen** [comment]
That would be great. I was also just trying to persist the needed changes. It might not look like much but it took hours to find the right css to solve this. So I don't want it to disappear. Thanks.

**Comment by philippjfr** [comment]
Can you explain what the `t-tdst` submodule in this PR is doing?

**Comment by MarcSkovMadsen** [comment]
No. But i will remove it

**Comment by philippjfr** [comment]
Looking at this now, I don't think the variable definitions here are needed. However I do need to understand how you generated the fast theme in the first place? It seems to be significantly outdated now causing issues like the fast list editor being rendered in the wrong place and much more. In the long run it does not seem entirely feasible to keep maintaining this custom theme since it basically require significant updates every time we bump the tabulator version.

**Comment by philippjfr** [comment]
Superseded by other PRs.

**Pull request closed without merging**
