### PR TITLE
Implement header filters on Tabulator

### PR DESCRIPTION
**Pull request by philippjfr**
Implements client-side filtering using the `header_filters` parameter.

Closes https://github.com/holoviz/panel/issues/2807

- [x] Add docs
- [x] Add tests

filtering

### CODE REVIEW

**Comment by maximlt** [comment]
When I try to filter the index (typing `1`) on this table
image
I get
```python


Traceback (most recent call last):
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/pyviz_comms/__init__.py", line 325, in _handle_msg
    self._on_msg(msg)
  File "/Users/mliquet/work/dev/panel/panel/viewable.py", line 273, in _on_msg
    doc.unhold()
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/document/document.py", line 799, in unhold
    self.callbacks.unhold()
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/document/callbacks.py", line 396, in unhold
    self.trigger_on_change(event)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/document/callbacks.py", line 373, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/util/callback_manager.py", line 191, in invoke
    callback(attr, old, new)
  File "/Users/mliquet/work/dev/panel/panel/reactive.py", line 303, in _comm_change
    self._process_events({attr: new})
  File "/Users/mliquet/work/dev/panel/panel/reactive.py", line 953, in _process_events
    super(ReactiveData, self)._process_events(events)
  File "/Users/mliquet/work/dev/panel/panel/reactive.py", line 263, in _process_events
    self.param.set_param(**self_events)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/mliquet/work/dev/panel/panel/widgets/tables.py", line 1062, in _update_cds
    super()._update_cds(*events)
  File "/Users/mliquet/work/dev/panel/panel/util.py", line 390, in wrapped
    fn(self, *args, **kwargs)
  File "/Users/mliquet/work/dev/panel/panel/reactive.py", line 654, in _update_cds
    self._processed, self._data = self._get_data()
  File "/Users/mliquet/work/dev/panel/panel/widgets/tables.py", line 911, in _get_data
    return super()._get_data()
  File "/Users/mliquet/work/dev/panel/panel/widgets/tables.py", line 359, in _get_data
    df = self._filter_dataframe(self.value)
  File "/Users/mliquet/work/dev/panel/panel/widgets/tables.py", line 262, in _filter_dataframe
    col = df[col_name]
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'index'
```

**Comment by maximlt** [comment]
> When a filter is applied clients-side it synced with Python ensuring that it works even in a paginated setup.

This sentence is a bit cryptic to me, could we just say that the filters also work in a paginated setup? (Assuming I correctly understood that)

**Comment by maximlt** [comment]
Is there a way to obtain the dataframe filtered using these client-side filters? (Same question actually with the filters added from the add_filter Python API 🙃 )

**Comment by maximlt** [comment]
`header_filters` should be listed at one of the parameters of Tabulator at the top level of the page.

I don't know the same should be done for `filters` however, would it be possible to set it to have the tabulator already filtered when constructed? By the way the docs could explicitly show that `[{'field': 'Director', 'type': '=', 'value': 'Steven Spielberg'}]` is the result of getting the `filters` attribute:
```
>>> filter_table.filters
[{'field': 'Director', 'type': '=', 'value': 'Steven Spielberg'}]
```

**Comment by philippjfr** [comment]
Appreciate the thorough review @maximlt!

**Comment by dslemusp** [comment]
Hi guys. I am trying to configure a `list` header filter enabling `multiselect` but it does not seem to work.

```python
table_filters = {
    "experiment_type": {"type": "list","multiselect":"true"},
}
pn_table = pn.widgets.Tabulator(
    experiments_df[["experiment_type"]], 
    pagination="remote", 
    page_size=30, 
    sizing_mode="stretch_width", 
    header_filters=table_filters
)
pn_table.show()
```

image


compared to the default beahviour

```python
table_filters = {
    "experiment_type": {"type": "list"},
}
pn_table = pn.widgets.Tabulator(
    experiments_df[["experiment_type"]], 
    pagination="remote", 
    page_size=30, 
    sizing_mode="stretch_width", 
    header_filters=table_filters
)
pn_table.show()
```

image

**Pull request merged**
