### PR TITLE
let FileInput widget set filename

### LINKED ISSUE #955: Fileinput widget always returns `None` for name of uploaded file
As of panel 0.7.0 (with bokeh 1.4.0), the Fileinput widget does not set the name of the uploaded file.

E.g. in the following code
```python
import panel as pn

inp = pn.widgets.FileInput(name='Upload')
btn = pn.widgets.Button(name='Upload', button_type='primary')
r= pn.Column(pn.Row(inp, btn),)

def on_click_parse(event):
    #print(inp.get_param_values())
    print(inp.filename)
btn.on_click(on_click_parse)

r.servable()
```
it always prints `None` to the terminal.

I can already see where the issue is and will open a PR.

### PR DESCRIPTION
**Pull request by ltalirz**
fixes #955 

The value of the `filename` property of the `FileInput` always remained
`None` (also after uploading a file).

I could add a test [here](https://github.com/holoviz/panel/blob/master/panel/tests/widgets/test_input.py#L63), if you let me know what the filename I should be testing for here.

### CODE REVIEW

**Comment by philippjfr** [comment]
This is great thank you!

>I could add a test here, if you let me know what the filename I should be testing for here.

Just do something like this:

```python
file_input._comm_change({'mime_type': 'text/plain', 'value': 'U29tZSB0ZXh0Cg==', 'filename': 'testfile'})

assert file_input.filename == 'testfile'
```

**Comment by ltalirz** [comment]
Done!

**Comment by philippjfr** [comment]
Looks like a syntax error snuck in there.

**Comment by philippjfr** [comment]
Thanks again!

**Pull request merged**
