### PR TITLE
Adding a DatetimePicker widget

### PR DESCRIPTION
**Pull request by Hoxbro**
As mentioned in #1975 I have been working on a `DatetimePicker`. This is based on the existing `DatePicker` already in Panel and Bokeh, so a lot of the code is reused from it. 

I could not get the value to be datetime in the Bokeh model, so I went with a simple string to communicate with the model. I also tried to inherit a lot of the code from the existing `DatePicker` but in the end it was easier to not do it.

The following code can be used to start the widget. 
``` python
from datetime import datetime, date

import panel as pn
pn.extension()


a = pn.widgets.DatetimePicker(
    name="Datetime2",
    start=date(2019, 2, 1),
    end=date(2022, 1, 1),
    value=datetime.today(),
    enable_time=True,
    enable_seconds=True,
    military_time=True,
).servable()
```
Example of the widget in action:
https://user-images.githubusercontent.com/19758978/111658738-e8b39380-880c-11eb-801c-fe24b14dab00.mp4

**TODO** 
- [ ] Adding documentation
- [ ] Adding unit test
- [ ] Properly some refactoring of the code
- [ ] Other things?

### CODE REVIEW

**Comment by philippjfr** [comment]
This is awesome, thank you! Is there an easy way to refactor this in such a way that we can add a DatetimeRange widget without duplicating too much code?

**Comment by jbednar** [comment]
Right; very often what I need to do is to choose a datetime range for which data to plot, so in practice I'm more often in need of a range than of a single datetime.

**Comment by Hoxbro** [comment]
This is definitely possible. I have a small example with it. Although it is not finished yet as I have not implemented it on the python/panel side, but it works in the browser/bokeh model. It should be pretty straight forward to implement it on the panel side, but this will be another day.

I have attached a video showcasing it, where the console logs a change in the widget.

https://user-images.githubusercontent.com/19758978/111920516-bb2a4c80-8a8f-11eb-94db-63ac8edc956c.mp4

**Comment by TvieiraB** [comment]
This looks great, can't wait to see it in Lumen.

**Comment by philippjfr** [comment]
This is great, thank you @Hoxbro. Will merge and do any cleanup tasks in another PR if I find anything.

**Pull request merged**
