### PR TITLE
How to reduce the launch time of your data app

### LINKED ISSUE #4280: Document how to speed up the launch of your app
Developing speedy apps is important for the user experience. Panel contains some descriptions of tools like the admin and profiling that can help you identify the bottlenecks. But there are no tips for removing the bottlenecks when identified. These requires some tricks that are not apparent or document.

Please create a how to that explains how to improve the load/ launch time of your data app.

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Closes #4280

You can preview the guide [here](https://github.com/holoviz/panel/blob/feature/document-how-to-load/doc/how_to/performance/reduce-launch-time.md).

## Todo

- [] Figure out how I can setup a pytest that includes the full scope of handling request and sending a response. I.e. something that corresponds to `CodeRunner.run`. That can be used for easy, repeated profiling and benchmark on the server side.

## Issues identified

- #4282
- #4283
- #4284
- #4285
- #4287

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
I use the word *launch* because that is used in the `--admin` tab for profiling the *launch*. But the word *load* is also sometimes used. For example in *load* testing. Let me know if you think there is a better term than *launch*.

**Comment by MarcSkovMadsen** [comment]
## Assets

**home.jpg**

home

**dashboard.jpg**

dashboard

**Comment by philippjfr** [comment]
Just some high-level comments to guide the direction of this. I'll start by quoting the Diataxis framework description of a how-to guide:

>How-to guides can be thought of as recipes, directions that guide the reader through the steps to achieve a specific end.

> How-to guides - task oriented, practical steps, that serve our work
> Examples could be: how to calibrate the radar array; how to use fixtures in pytest; how to configure reconnection back-off policies. On the other hand, how to build a web application is not - that’s not addressing a specific goal or problem, it’s a vastly open-ended sphere of skill.

> How-to guides matter not just because users need to be able to accomplish things: the list of how-to guides in your documentation helps frame the picture of what your product can actually do. A rich list of how-to guides is an encouraging suggestion of a product’s capabilities.

The current content here seems very valuable but it doesn't really fit into a the structure of a how-to guide. I suspect we'll have to add background sections to link to, to explain in detail how a server session is managed and created (and how that relates to performance).  From there I suggest we break things down into individual, narrowly scoped guides, e.g.:

- How to identify bottlenecks in your application?
    - Chrome
    - Admin page + Profiler

And then maybe have a flowchart that highlights common sources of performance issues and links to specific section that help you address those.

**Comment by MarcSkovMadsen** [comment]
Thanks for the input. I hope its ok to let me write the document first and the try to split it up? I don't really know where it ends before I have worked a bit on this.

**Comment by philippjfr** [comment]
There's still a lot of valuable stuff in here and it overlaps a bit with @ahuang11's suggestion of adding a best practices guide. So I'd suggest that I close this for now but perhaps Andrew could revive this in form of a "Performance Checklist" how-to guide.

**Comment by ahuang11** [comment]
listed here to not get lost
https://discourse.holoviz.org/t/personal-opinions-about-best-practices-for-panel-holoviews/6789/26

**Pull request closed without merging**
