### PR TITLE
Add Python 3.10 and 3.11 support

### PR DESCRIPTION
**Pull request by maximlt**
Python 3.11 just got out, let's try to get the CI running on 3.10 again.

EDIT:
This PR says that it's adding Python 3.10 and 3.11 support but all that it's really doing is:

- setup the CI to run on these versions, which at the time of writing involves not running the examples! As even on Python 3.10 all the dependencies aren't yet available on conda-forge.
- make the test suite a little more robust by doing some minor changes here and there in the test suite
- make the CI only run on 3.7, 3.9 and 3.11, except on scheduled, tag, and manually dispatched events where it runs the full set from 3.7 to 3.11.
- run the docs Markdown part of the examples tests, as they need the examples dependencies.

### CODE REVIEW

**Comment by philippjfr** [comment]
Let's use this PR to also fix the rest of the CI. It's in pretty poor shape right now.

**Comment by maximlt** [comment]
> Let's use this PR to also fix the rest of the CI. It's in pretty poor shape right now.

I agree.

**Comment by philippjfr** [comment]
Looking good, and thanks for doing this!

**Comment by maximlt** [comment]
It's not yet ready!

**Comment by philippjfr** [comment]
Just showing appreciation for you 🤗

**Review by philippjfr — APPROVED** [review]
Looks good, thank you!

**Comment by maximlt** [comment]
Oh it just failed when I wrote the last message :( Seems there are intermittent install failures on Windows / Python 3.7. I might just remove it from the matrix. Anyway, interested in your feedback on this.

**Pull request merged**
