### PR TITLE
Add CSS on mouse interaction with card

### PR DESCRIPTION
**Pull request by ahuang11**
Better notify the user that it's clickable and makes it feel nicer.

- Update pointer on hover
- Lower contrast upon hover

https://github.com/holoviz/panel/assets/15331990/7757e6f0-3043-45ff-858a-14c1988e18d1

### CODE REVIEW

**Comment by Hoxbro** [comment]
Can't this be done with CSS?

**Comment by ahuang11** [comment]
Templates + original with these changes
image
image
image
image

**Comment by philippjfr** [comment]
Reducing contrast on hover seems a little counter-intuitive, I'll try to come up with a different visual change but am open to your suggestions.

**Comment by ahuang11** [comment]
Brightness didn't seem to work for me. Opacity is worse than contrast. Transform is a little strange so I stuck with contrast. Color maybe could change to theme accent

1. **Opacity**: Adjusting the opacity of an element can create a subtle hover effect.
   ```css
   .card-button:hover {
     opacity: 0.8;
   }
   ```

2. **Brightness**: The `brightness()` filter can be used to control the brightness of an element.
   ```css
   .card-button:hover {
     filter: brightness(0.8);
   }
   ```

3. **Box Shadow**: Adding a box shadow can create a sense of depth and highlight on hover.
   ```css
   .card-button:hover {
     box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
   }
   ```

4. **Transform Scale**: Scaling the element slightly on hover can provide a nice visual effect.
   ```css
   .card-button:hover {
     transform: scale(1.1);
   }
   ```

5. **Color**: Changing the color of the element on hover can draw attention.
   ```css
   .card-button:hover {
     color: #ff0000; /* Change to the desired color */
   }
   ```

**Comment by philippjfr** [comment]
I'd be okay with a box-shadow of some sort.

**Comment by ahuang11** [comment]
Here's box shadow.
https://github.com/holoviz/panel/assets/15331990/0465a949-b50b-425b-9558-e5c50ae1674c

**Review by philippjfr — APPROVED** [review]

**Pull request merged**
