### PR TITLE
Clarified wording in best practices docs

### PR DESCRIPTION
**Pull request by jbednar**
Added additional explanation where I thought it would be helpful.

### CODE REVIEW

**Comment by Coderambling** [comment]
Very useful! Especially the more verbose emphasis on the distinction between parameter as an object, and the value of a parameter.

Would be good to state the distinction that explicitly in all the docs where applicable.

**Review by ahuang11 — APPROVED** [review]
Thanks for the additional clarifications!

**Comment by jbednar** [comment]
Waiting on https://github.com/holoviz/panel/pull/7286 to fix the CI.

**Comment by Coderambling** [comment]
Very useful additions to the best practices document.

One remark: the paragraph below inthe doc ends with:

> because `Viewer` allows direct invocation of the class, resembling a native Panel object.

With "invocation of the class", do you mean invocation of the `param.Parameterized` class? Or if not, what class? Would be good to make this more explicit in the sentence.

> Instead of inheriting from `param.Parameterized`, using `pn.viewable.Viewer` allows direct invocation of the class, resembling a native Panel object.
`param.Parameterized` is a very general class that can be used separately from Panel for working with Parameters. But if you want a Parameterized class to use with Panel, it is usually appropriate to inherit from the Panel-specific class `pn.viewable.Viewer` instead, because `Viewer` allows direct invocation of the class, resembling a native Panel object.

**Comment by jbednar** [comment]
> With "invocation of the class", do you mean invocation of the param.Parameterized class? Or if not, what class? Would be good to make this more explicit in the sentence.

I think that's a question for @ahuang11 , who can hopefully clarify that bit of the text!

**Pull request merged**
