### PR TITLE
Set Bokeh logging to INFO

### LINKED ISSUE #2302: panel serve logs stops working when importing datashader
#### ALL software version info
Windows 10  20H2
holoviews 1.14.3
panel 0.11.3
datashader 0.12.1

#### Description of expected behavior and the observed behavior
I'm not sure if this a `panel`, `datashader`, or a `holoviews` issue. 
The problem is when importing `holoviews.operation.datashader` in my file, the logging in the command window stops sending logs. When running`panel serve tmp.py --autoreload` with  `holoviews.operation.datashader` imported no logs show up at all and I have to guess when ready. 

#### Complete, minimal, self-contained example code that reproduces the issue
``` python
import panel as pn
import holoviews.operation.datashader

pn.panel("# Test").servable()

```
And run the command `panel serve` or `panel serve --autoreload`

#### Screenshots or screencasts of the bug in action

|  | No `datashade` import | `datashade` import |
|--|--|--|
| Without `--autoreload` |    |   |
| With `--autoreload`    |   |    |

### PR DESCRIPTION
**Pull request by hoxbro**
Fixes #2302

Beforehand, this will not output logs because  `distributed` sets the logger level to error. Not sure if we need to have a setting for this. 

``` python
import distributed  # noqa
import panel as pn
pn.panel("A").servable()
```

### CODE REVIEW

**Comment by maximlt** [comment]
I want to carefully review this as I have code that relies on logging and have found that setting this up is difficult in general.

**Comment by philippjfr** [comment]
@maximlt How's the careful review going? 😄

**Comment by maximlt** [comment]
It looks like I have *carefully* managed not to get to review it :( I promise this will be done this week!

**Review by maximlt — COMMENTED** [review]
(I rebased this PR to be able to test it).

I'm -1 on the change as is. It's setting the log level of Bokeh's logger to `INFO`, ignoring what the user may have configured via `BOKEH_PY_LOG_LEVEL` or `--log-level` or whatever logger customisation they might have done in a `--setup` file.

I opened an issue to report the problem upstream https://github.com/dask/distributed/issues/8750.

**Comment by maximlt** [comment]
There's in fact already a PR to stop setting the logs on import https://github.com/dask/distributed/pull/8634.

**Pull request closed without merging**
