### PR TITLE
VTK 3D multi slice 

### PR DESCRIPTION
**Pull request by xavArtley**
PR to implement a multi slice of 3d data volumes
In the same time I refactor some parts of VTK models

### CODE REVIEW

**Comment by xavArtley** [comment]
New volume control exposed 
image

**Comment by xavArtley** [comment]
I merged the 3d slicer with the volume pan
ezgif com-video-to-gif (10)

**Comment by xavArtley** [comment]
I exposed the interpolation type, now we have real boxes when using nearest interpolation
image

**Comment by xavArtley** [comment]
Last thing to do is to update the reference notebook

**Comment by philippjfr** [comment]
Thanks so much @xavArtley! I think the docs are largely fine for now and we can expand on them later.

**Pull request merged**
