### PR TITLE
Switch to conda-incubator in GH Actions

### PR DESCRIPTION
**Pull request by philippjfr**

### CODE REVIEW

**Comment by mattpap** [comment]
@philippjfr, I'm wondering what's the relationship between conda-incubator and conda (team)?

**Comment by philippjfr** [comment]
Good question, I don't think there is one. I know there's been a conda consortium formed with various stakeholders (conda core, conda-forge, mamba etc.) but this seems to be primarily driven by conda-forge and Quansight folks.

**Comment by mattpap** [comment]
OK. I will apply this to bokeh's CI.

**Comment by philippjfr** [comment]
I was seeing various errors with the old version (i.e. Gonzalo's goanpeca) so decided to switch over. It also seems he just migrated it over to the conda-incubator org.

**Comment by mattpap** [comment]
It's actually a good timing I saw your PR, because my PRs in bokeh started failing. I also see there was a deprecation notice in logs, but given their volume, it went unnoticed.

**Pull request merged**
