### PR TITLE
Add editable sliders

### PR DESCRIPTION
**Pull request by philippjfr**
```python
float_slider = pn.widgets.EditableFloatSlider(name='EditableFloatSlider', editable=False) 
int_slider = pn.widgets.EditableIntSlider(name='EditableIntSlider', end=10)
range_slider = pn.widgets.EditableRangeSlider(name='EditableRangeSlider', editable=(False, True))
pn.Column(float_slider, int_slider, range_slider)
```

Screen Shot 2021-03-22 at 3 30 22 PM

- [ ] Add tests
- [x] Add docs

### CODE REVIEW

**Comment by jbednar** [comment]
Thanks so much! Fixes https://github.com/holoviz/panel/issues/675 and (most of?) https://github.com/holoviz/panel/issues/1128 , plus can help address https://github.com/bokeh/bokeh/issues/9943 for Bokeh users willing to include Panel in their dependencies.

Is it possible to tweak the CSS involved here?  It would be great if we could have editable sliders that are approximately the same cost (in space and visual complexity) as the non-editable sliders, which seems doable to me. Can we have anything like the following options?

1. Simply removing the box around the spinner, which seems doable though a bit funny looking (and maybe no worse than before?): 

2. Reserving only a single digit for the numerical value, automatically expanding it (and shrinking the slider width to compensate) as the size expands (which seems unlikely to be doable when dragging the slider; likely to have the text overwrite the slider without doing major magic):

3. Getting rid of the spinner's box and moving it to where the slider value is normally shown, eliminating any border space taken by the spinner box:

**Comment by jbednar** [comment]
For comparison, the non-editable versions would look roughly like this, i.e. the same as option 3 above but without any gray text and without the spinner widgets:

**Comment by philippjfr** [comment]
Latest version after visual tweaks:

Screen Shot 2021-03-29 at 2 28 31 PM

**Comment by jbednar** [comment]
Very cool, thanks!  Let's try this out for a while, and then maybe at some point consider whether to make it the default for a Param.Number mapping.

**Pull request merged**
