### PR TITLE
fix root_dir support for "Render with Panel" green button 

### PR DESCRIPTION
**Pull request by tlvu**
Regression introduced when calling `fullpath(path)` when `path` is an URL fragment.  I think `fullpath()` was meant for path on disk only.

See discussion in https://github.com/holoviz/panel/issues/3440#issuecomment-1112616866

### CODE REVIEW

**Comment by tlvu** [comment]
This is really odd, my fix seems to make the JupyterLab server restart each time I save the notebook to test the "Render on Save" checkbox.

This is my first PR.  I do not really understand how this plugin is interacting with JupyterLab.  Please help.

**Comment by philippjfr** [comment]
Thanks @tlvu. I'll look at this later today, want this in 0.13.1 which I hope to release today or Monday.

**Comment by philippjfr** [comment]
So I don't see the issue you're seeing at all. This works perfectly for me, and I can confirm that adding `fullpath` caused issues when setting the `--notebook-url`.

**Comment by philippjfr** [comment]
So I don't see the mechanism by which this could force a restart either. The server extension is simply installed as an additional handler on the tornado server. If it's somehow killing or resetting jupyterlab then there's something else going on causing it to crash.

**Comment by tlvu** [comment]
>  If it's somehow killing or resetting jupyterlab then there's something else going on causing it to crash.

@philippjfr You're right, completely my fault.  I had `--autoreload` given to `jupyter lab` and I forgot about it.  Sorry for the false alarm.  "Render on Save" checkbox works very well now.

While continuing to investigate the restart issue above, I noticed this line https://github.com/holoviz/panel/blob/e28703da931b29a06c75c47a689b7fa243a99b77/panel/io/jupyter_server_extension.py#L108

Given `path` is now really "full path on disk" and not a URL fragment anymore, that line seems wrong.  But when testing I do not observe anything wrong.  Is it worth to still fix that line?

**Comment by philippjfr** [comment]
Thanks @tlvu. Good catch, I don't think the ApplicationContext.url value is used for anything important, which is why it seems to have no adverse consequences. Should still fix it though.

**Pull request merged**
