### PR TITLE
Implement Tabulator buttons

### PR DESCRIPTION
**Pull request by philippjfr**
If you want to trigger custom actions by clicking on a table cell you may declare a set of `buttons` that are rendered in columns after all the data columns. To respond to button clicks you can register a callback using the `on_button_click` method:

button_click

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Wow. Some one thinks tables are important. I do too. Love it.

**Comment by MarcSkovMadsen** [comment]
I wondered about the use cases. I would say some very popular ones are "download file" and "open url". Are they easy to implement with these buttons @philippjfr ?

**Comment by maximlt** [comment]
I've just tried it and the event returns the row number, not the row index. Which means that to get a value one has to write something like `df.loc[df.index[event.row], 'URL']`. Returning the row index might be a little simpler for users, or the whole row data.

**Comment by philippjfr** [comment]
That's what we do for selections and the expanded parameter as well, you should just be able to use `iloc` like this:  `df.iloc[event.row]`

**Comment by maximlt** [comment]
I just find working with indexes usually more natural than working with row numbers but if this is what is already done elsewhere then let's favor being consistent. (This is concise enough anyway: `df.iloc[event.row]['URL']`)

**Comment by jbednar** [comment]
Sounds like that iloc usage ought to be illustrated in the docs?

**Comment by contang0** [comment]
is there a way to move button position to the left of the table?

**Pull request merged**
