### PR TITLE
Add DeckGL pane [doc-build]

### PR DESCRIPTION
**Pull request by philippjfr**
Supersedes #960 

Fixes https://github.com/holoviz/panel/issues/957

### CODE REVIEW

**Comment by philippjfr** [comment]
@MarcSkovMadsen Thanks so much for getting this started! Getting this to work reliably in Jupyter notebooks and JupyterLab was a huge pain but I've worked out a solution. In JupyterLab (and on the server) we load the individual dependencies while in Jupyter notebooks we load the pydeck jupyter-widget bundle (as you were doing). The former is more efficient overall and really this is kind of hacky but I hope eventually we can have smaller bundles which consistently load the components using npm or get a better mechanism for loading the JS dependencies lazily. For now I'm very happy to have this in 0.8! This should be the last code PR to go in and I should be ready to release tomorrow.

**Comment by MarcSkovMadsen** [comment]
Hi @philippjfr 

I'm so impressed. I could have spent a week on this. Don't know how you know how to do all these things :-)

One thing that might be interesting is that I have a more advanced example of using the DeckGL pane. I will create a new pull request to include that.

**Comment by philippjfr** [comment]
>I'm so impressed. I could have spent a week on this. Don't know how you know how to do all these things :-)

Ha, don't put yourself down, you got things 90% there, I just did all the tedium of making things work across across different environments (honestly I wanted to pull my hair out on this) and updating it to the new build infrastructure.

>One thing that might be interesting is that I have a more advanced example of using the DeckGL pane. I will create a new pull request to include that.

Yes, we need to get the gallery more populated somehow. At some point soon I'll ask people to contribute their examples back to the gallery. A more complex DeckGL example would be hugely appreciated.

**Comment by jbednar** [comment]
> A more complex DeckGL example would be hugely appreciated.

More complex examples should probably be part of examples.pyviz.org, not Panel itself, so that they can have their own separate pinned environment rather than necessarily being updated during every Panel release...

**Pull request merged**
