### PR TITLE
Avoid events boomeranging from frontend

### PR DESCRIPTION
**Pull request by philippjfr**
This adds a long overdue change which ensures that events arriving from the frontend do not boomerang. There was a previous attempt at doing this but instead of skipping events being applied that originated on the frontend it cancelled the processing of new events after a property change was made. These approaches have potentially similar effects but in fact are quite different, since the old change effectively would potentially cause a property to revert to an older value.

Fixes https://github.com/holoviz/panel/issues/7096
Fixes https://github.com/holoviz/panel/issues/6738
Fixes https://github.com/holoviz/panel/issues/6414

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Will this solve issue with ChatInterface? I.e. the problem that if you don't type slowly then text will disappear?

**Comment by philippjfr** [comment]
>Will this solve issue with ChatInterface? I.e. the problem that if you don't type slowly then text will disappear?

I have never encountered that problem, the problem it is meant to solve is that the chat feed scroll position isn't stable.

**Comment by MarcSkovMadsen** [comment]
I will make a separate issue then.

**Comment by philippjfr** [comment]
A reproducer would be very helpful. I definitely can't reproduce this with a bare chat interface.

**Comment by MarcSkovMadsen** [comment]
Hmmm. The problem is only with the deployed app. When developing on jupyter hub with proxy server there is no problem. That is strange as it should be the same. But I also experience my deployed apps being slower even though they have the same resources available.

**Comment by philippjfr** [comment]
Yeah literally never seen it and we have many chat apps in production with different clients.

**Comment by duarteocarmo** [comment]
Hey @philippjfr any idea when this will be available? (I know 1.4.5, just wondering if there is a release date for that, or an option to release it sooner?)

Thanks!

**Comment by duarteocarmo** [comment]
We are observing the same issue as @MarcSkovMadsen in #7096

**Comment by philippjfr** [comment]
I was planning to cut 1.5.0rc1 today and then make the proper release some time next week.

**Comment by duarteocarmo** [comment]
Awesome - appreciate it. 👍🏻

**Pull request merged**
