### PR TITLE
Upgrade to Tabulator 5.3.2

### PR DESCRIPTION
**Pull request by maximlt**
Fixes https://github.com/holoviz/panel/issues/3695

### CODE REVIEW

**Comment by maximlt** [comment]
@philippjfr I expected this test - `test_tabulator_header_filter_no_horizontal_rescroll[None]` - to fail. It tests that when you have a wide table with an horizontal scrollbar, then after scrolling right, setting a header filter shouldn't update the scroll position. What happens after the upgrade is that the header filter entirely disappears! I've added a test that checks that this doesn't occur all the time, i.e. it seems to only happen when there's a horizontal scrollbar. Tabulator JS now emits more warnings when events are triggered when they should not, there are a few warnings triggered when the widget is rendered, so maybe that's an area to explore to try to fix that. I've attempted to change some of that logic, without luck unfortunately.

**Comment by maximlt** [comment]
Testing this on real apps, I've seen many warnings related to events being triggered when they shouldn't (redraw in particular). I've also seen this error multiple times: `Uncaught (in promise) TypeError: Cannot read properties of null (reading offsetWidth)`.

**Comment by philippjfr** [comment]
> What happens after the upgrade is that the header filter entirely disappears! I've added a test that checks that this doesn't occur all the time, i.e. it seems to only happen when there's a horizontal scrollbar.

So it doesn't actually disappear, the problem is that the scrollbar disappears when there are no rows, which in turn means you cannot see all the rows in the header. Not sure I'll be able to resolve this immediately.

>Tabulator JS now emits more warnings when events are triggered when they should not, there are a few warnings triggered when the widget is rendered, so maybe that's an area to explore to try to fix that. I've attempted to change some of that logic, without luck unfortunately.

Got a fix for this I'll push up shortly.

**Comment by philippjfr** [comment]
>Not sure I'll be able to resolve this immediately.

I did resolve it. Had to add this:

```javascript
  this.tabulator.on("dataFiltered", (_: any, rows: any[]) => {
      if (this._initializing)
	return
      // Ensure that after filtering empty scroll renders
      if (rows.length === 0)
	this.tabulator.rowManager.renderEmptyScroll()
      // Ensure that after filtering the page is updated
      this.updatePage(this.tabulator.getPage())
    })
```

**Pull request merged**
