### PR TITLE
Allow to convert a Color Parameter with `allow_None=True` to a Bokeh property

### PR DESCRIPTION
**Pull request by maximlt**
Fixes https://github.com/holoviz/panel/issues/3058

```python
# The Bokeh Color property has `_default_help` set which causes
# an error to be raise when Nullable is called on it. This converter
# overrides the Bokeh _help to set it to None and avoid the error.
```

While this fixes the issue linked I'm not sure it's a good long term solution:
* It might well be a bug in Bokeh
* The only two properties that have `_default_help` set are `Color` and `Alpha` (`Alpha` causes no problem since it has no Parameter type associated). But if a mapped property (e.g. `String`) gets its `_default_help` set then we'll likely encounter the same error.

### CODE REVIEW

**Comment by philippjfr** [comment]
@mattpap Any idea what best to do here? Seems to me like this either shouldn't be an error condition. All properties should let you wrap it in `Nullable` without erroring.

**Comment by mattpap** [comment]
> Any idea what best to do here? Seems to me like this either shouldn't be an error condition. All properties should let you wrap it in Nullable without erroring.

The error condition is there to help one realize something is off with their properties' setup, e.g. having:
```py
prop = Nullable(Color(help="help"))
```
instead of
```py
prop = Nullable(Color, help=help)
```
The issue comes from different treatment of top-level properties, which become basis for descriptors, and inner properties (type parameters), which only serve type-related purpose (validation, serialization).

**Comment by mattpap** [comment]
At least in `branch-3.0`, one can wrap `Color` in `Nullable`, unless explicit `help` is given:
```py
In [1]: from bokeh.models import *

In [2]: from bokeh.core.properties import *

In [3]: class T0(Model):
   ...:     p0 = Color(help="p0")
   ...: 

In [4]: class T1(Model):
   ...:     p1 = Nullable(Color, help="p1")
   ...: 

In [5]: class T2(Model):
   ...:     p2 = Nullable(Color(help="p2"))
   ...:    
ValueError: setting 'help' on type parameters doesn't make sense
```

**Comment by mattpap** [comment]
One thing we may consider doing, is merging help, but that may have limited utility.

**Comment by philippjfr** [comment]
Thanks @maximlt. Will merge with the workaround.

**Pull request merged**
