### PR TITLE
Allow streaming chunks to HTML panes

### PR DESCRIPTION
**Pull request by philippjfr**
Often, especially for the chat interfaces you are slowly streaming chunks to the frontend. Currently however, we send the entire text every time any of it is updated. This PR proposes to add a `stream` parameter to HTML based components, e.g. like `HTML` itself or `Markdown`. When enabled the pane will find the length of overlap and then simply sends the non-overlapping chunk to to the frontend using a server-side event, massively reducing the amount of text sent to the frontend. Since this can lead to super rapid updates we currently batch the incoming messages and apply the update at most every 10 ms.

Unfortunately for large messages this quickly runs into this issue: https://github.com/holoviz/panel/issues/6603

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Is there not a more general way to diff a string based on position?

Then instead of s new stream parameter we could keep using the value parameter.

**Comment by philippjfr** [comment]
I think you're misunderstanding the PR, the `stream` parameter is a boolean toggle which determines whether to send diffs or not.

**Comment by philippjfr** [comment]
Okay, sorry reading back your reply I misread it. Generally I agree and I'd be okay with a `mode` or `diff_mode`, that said streaming is really the main scenario where you send tons of small individual updates. If you're editing a large document you might want to send smaller patches but finding the patches becomes computationally expensive and in many cases may not be worth it.

**Comment by MarcSkovMadsen** [comment]
Makes sense. 

If `stream` is the only additional *mode* we will ever support then calling it `stream` is fine.

**Comment by philippjfr** [comment]
>I think my context is coming from streamlit. My understanding is that they have a virtual document on the python side and only send diff patches using protobuf.

Do you know of a good writeup of this? This sounds more analogous to the bokeh document than diffing of the contents of an individual update but I'd love to know more.

**Pull request merged**
