### PR TITLE
Add a method to expose Param mapping

### LINKED ISSUE #620: param types vs panel widgets
The docs (https://panel.pyviz.org/user_guide/Param.html) tell us that
> internally Panel maintains a mapping between parameter types and widget types.

I think it would be helpful if we could explicitly list this mapping in the docs, i.e. which widget a given param type is translated to.

### PR DESCRIPTION
**Pull request by maximlt**
Fixes #620

### CODE REVIEW

**Comment by jbednar** [comment]
Looks good! Is the mapping that is returned modifiable in place, as an alternative to passing in a partial mapping in certain API calls?  If so I think that should be mentioned in its docstring and in the docs that were modified here.

**Comment by philippjfr** [comment]
I'm also wondering this. IMO we should not make it modifiable directly returning some immutable view of the mapping and providing some API to override it, or we should just make the mapping attribute public.

**Comment by jbednar** [comment]
I'd vote for making the mapping attribute a public Parameter, so that people can easily configure it how they like at the start of a body of code, then forget about it.

**Comment by MarcSkovMadsen** [comment]
Yes. I would need to be able to update the mapping I believe when I have a library of mwc web components widgets that I would like to use instead. But as far as I remember not everything happens in the mapping. There are also code (if statements) determining what happens.

**Comment by jbednar** [comment]
Good point.  I haven't looked at it, but there might be a way to map that logic into the mapping (no pun intended).  For instance, we could define some extra key, value pairs, where the key is a special value, not just a bare Parameter type.  That way the logic can select the special value when special cases are needed, and the static mapping can then statically map that value to a user-selectable type.

**Comment by xavArtley** [comment]
If we make the mapping modifiable it would be nice to also be able to configure the default parameters of widgets in this mapping

**Comment by maximlt** [comment]
Good to see this has generated some interesting discussion 😉 

The original intent was just to display the mapping so that users don't have to read the code to understand why *that* param type was displayed with *that* widget. I wasn't so sure that returning a view on the mapping was a good idea, obviously it was not!

It seems that making the mapping public is the general idea now. Before doing that the first step would be to change the code to remove any internal logic related to the current mapping.

**Comment by philippjfr** [comment]
Superseded by #3173

**Pull request closed without merging**
