### PR TITLE
defined callback_user in lines 104 and 382

### PR DESCRIPTION
**Pull request by shwetabh-23**
I added the line : 
callback_avatar = param.ClassSelector(class_=(str, BinaryIO), doc="""
        The default avatar to use for the entry provided by the callback.
        Takes precedence over `ChatEntry.default_avatars` if set; else, if None,
        defaults to the avatar set in `ChatEntry.default_avatars` if matching key exists.
        Otherwise defaults to the first character of the `callback_user`.""")
and changed line : 
avatar = None

to : 
avatar = self.callback_avatar

### CODE REVIEW

**Comment by ahuang11** [comment]
Thanks for creating this!

Could you please run
`pre-commit install`

Also, can you add a few tests like https://github.com/holoviz/panel/commit/a1420603fb5da14d45c106e3813a5b38f7a3b1aa#diff-5408514bec6f5895a04fa7826621bcce676dd161c74eff71bce900e6c677a584L595-L600

**Comment by shwetabh-23** [comment]
I ran the "pre-commit install" as suggested and added a line (384): 

user = self.callback_user
        avatar = self.callback_avatar

        assert avatar == "👨"
let me know if this is correct or if some modifications are to be made

**Comment by shwetabh-23** [comment]
I cannot find both files at the mentioned directories. Please confirm from your end. in the main directory (https://github.com/holoviz/panel/tree/main), I get to panel/tests/widgets and there is no test_chat.py file and no chat.py file at panel/widgets. what is going wrong?

**Comment by ahuang11** [comment]
Woops, we moved them to panel/tests/chat/

**Comment by shwetabh-23** [comment]
okay, can you verify if this is correct? I've added an assertion in the test_feed.py file under the function test_default_avatars_superseded_by_callback_avatar.

**Comment by ahuang11** [comment]
I'd explicitly set callback_avatar somewhere.

**Comment by ahuang11** [comment]
Implemented in https://github.com/holoviz/panel/pull/6958

**Pull request closed without merging**
