### PR TITLE
Add Vizzu tooltip support

### PR DESCRIPTION
**Pull request by philippjfr**
Implements https://github.com/holoviz/panel/issues/5255

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
There vizzu docs have been updated and a few links in our reference notebook do not work any more. Let me document them below.

**Comment by MarcSkovMadsen** [comment]
- vizzu.Anim is now https://lib.vizzuhq.com/latest/reference/modules/Anim/
- vizzu.Config.Chart is now https://lib.vizzuhq.com/latest/reference/interfaces/Config.Chart/

**Comment by MarcSkovMadsen** [comment]
The links in the param docstrings are also invalid.

**Comment by philippjfr** [comment]
Thank you! I was also finally able to remove the forced re-render when the data is updated, which means animations now work when streaming, patching and updating data.

**Pull request merged**
