### PR TITLE
Add dimensions and prevent_collision to ReactTemplate.

### PR DESCRIPTION
**Pull request by syamajala**
Added dimensions argument for setting minW, minH, maxW, maxH and preventCollision argument for ReactTemplate.

### CODE REVIEW

**Comment by philippjfr** [comment]
This is great thanks. Could you document these variables in https://github.com/holoviz/panel/blob/master/examples/reference/templates/React.ipynb?

**Comment by syamajala** [comment]
I updated the documentation.

**Comment by philippjfr** [comment]
Perfect thank you!

**Comment by philippjfr** [comment]
Thanks, looks good! Unfortunately I've also got to ask you to update the failing test:

```python
    def test_react_template(document, comm):
        tmplt = ReactTemplate(title='BasicTemplate', header_background='blue', header_color='red')
    
        tmplt._update_vars()
        tvars = tmplt._render_variables
    
        assert tvars['app_title'] == 'BasicTemplate'
        assert tvars['header_background'] == 'blue'
        assert tvars['header_color'] == 'red'
        assert tvars['nav'] == False
        assert tvars['busy'] == True
        assert tvars['header'] == False
        assert tvars['rowHeight'] == tmplt.row_height
        assert tvars['breakpoints'] == tmplt.breakpoints
        assert tvars['cols'] == tmplt.cols
    
        markdown = Markdown('# Some title')
        tmplt.main[:4, :6] = markdown
    
        markdown2 = Markdown('# Some title')
        tmplt.main[:4, 6:] = markdown2
    
>       assert tvars['layouts'] == {
            'lg': [{'h': 4, 'i': '1', 'w': 6, 'x': 0, 'y': 0},
                   {'h': 4, 'i': '2', 'w': 6, 'x': 6, 'y': 0}],
            'md': [{'h': 4, 'i': '1', 'w': 6, 'x': 0, 'y': 0},
                   {'h': 4, 'i': '2', 'w': 6, 'x': 6, 'y': 0}]
        }
E       AssertionError: assert {'lg': [{'h':...inity', ...}]} == {'lg': [{'h':...'x': 6, ...}]}
E         Differing items:
E         {'md': [{'h': 4, 'i': '1', 'maxH': 'Infinity', 'maxW': 'Infinity', ...}, {'h': 4, 'i': '2', 'maxH': 'Infinity', 'maxW': 'Infinity', ...}]} != {'md': [{'h': 4, 'i': '1', 'w': 6, 'x': 0, ...}, {'h': 4, 'i': '2', 'w': 6, 'x': 6, ...}]}
E         {'lg': [{'h': 4, 'i': '1', 'maxH': 'Infinity', 'maxW': 'Infinity', ...}, {'h': 4, 'i': '2', 'maxH': 'Infinity', 'maxW': 'Infinity', ...}]} != {'lg': [{'h': 4, 'i': '1', 'w': 6, 'x': 0, ...}, {'h': 4, 'i': '2', 'w': 6, 'x': 6, ...}]}
E         Full diff:
E           {
E            'lg': [{'h': 4,
E                    'i': '1',
E         +          'maxH': 'Infinity',
E         +          'maxW': 'Infinity',
E         +          'minH': 0,
E         +          'minW': 0,
E                    'w': 6,
E                    'x': 0,
E                    'y': 0},
E                   {'h': 4,
E                    'i': '2',
E         +          'maxH': 'Infinity',
E         +          'maxW': 'Infinity',
E         +          'minH': 0,
E         +          'minW': 0,
E                    'w': 6,
E                    'x': 6,
E                    'y': 0}],
E            'md': [{'h': 4,
E                    'i': '1',
E         +          'maxH': 'Infinity',
E         +          'maxW': 'Infinity',
E         +          'minH': 0,
E         +          'minW': 0,
E                    'w': 6,
E                    'x': 0,
E                    'y': 0},
E                   {'h': 4,
E                    'i': '2',
E         +          'maxH': 'Infinity',
E         +          'maxW': 'Infinity',
E         +          'minH': 0,
E         +          'minW': 0,
E                    'w': 6,
E                    'x': 6,
E                    'y': 0}],
E           }
```

**Comment by syamajala** [comment]
I updated the test. It passes for me now.

**Comment by philippjfr** [comment]
Thanks again @syamajala! Your contribution is very much appreciated.

**Pull request merged**
