### PR TITLE
Support async functions on ParamMethod/ParamFunction

### PR DESCRIPTION
**Pull request by philippjfr**
Allows an approach like this:

```python
import aiohttp

widget = pn.widgets.IntSlider(start=0, end=10)

async def get_img(index):
    async with aiohttp.ClientSession() as session:
        async with session.get(f"https://picsum.photos/800/300?image={index}") as resp:
            return pn.pane.JPG(await resp.read())
            
pn.Column(widget, pn.bind(get_img, widget))
```

### CODE REVIEW

**Comment by philippjfr** [comment]
Linux 3.6 test failure is spurious.

**Comment by MarcSkovMadsen** [comment]
How would it work with `pn.panel(pn.bind(get_img, widget), loading_indicator=True`? Would the loading indicator be shown while the image is being loading async? That would be awesome.

**Comment by philippjfr** [comment]
Correct! Considering whether to just enable that by default.

**Comment by MarcSkovMadsen** [comment]
The problem is that if a function is fast. Then trying to show the loading indicator actually slows down your application. Or at least it feels like that to the user. 

Somehow the loading indicator should first be started after maybe 0.5 seconds or so ??

**Comment by philippjfr** [comment]
Good point, I think because of that it's probably best left up to the user. Don't want to be in the business of timing user callbacks.

**Pull request merged**
