### PR TITLE
Custom Colors in Fast Templates

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Addresses #2175

I would like to enable specifying a custom background, neutral and accent color for the FastListTemplate and FastGridTemplate. Both for the main area and for the header.

If possible I would like to implement it in a way that we user can also experiment with different colors, fonts and more like shown below.

https://user-images.githubusercontent.com/42288570/117608968-646ff380-b15f-11eb-8b64-25743387e3c0.mp4

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Please note that I cannot get the `--container-background` css variable added so I've left that hard coded for now. I have asked on the Fast Discourse how to add this one. See https://discord.com/channels/449251231706251264/482296787021856768/841167712217858058

**Comment by philippjfr** [comment]
What I'd love to do is expose it via a ReactiveHTML component so you can dynamically update the colors. Would be happy to help with a implementation.

**Comment by MarcSkovMadsen** [comment]
But after having thought about it. I think that the scope of this PR will be getting the custom branding/ color working on Template construction. And a separate PR will address the dynamic configuration. Because the first part is a "blocker" for some users. The second part is the "show off" part.

**Comment by MarcSkovMadsen** [comment]
Ready for review.

It would be nice to additionally

- Validation of color parameters. The Fast .js libraries only accept hex or rgb values
- Find some way to also set the `accent` color of the `index.html` template also, so that it is also "branded"

https://user-images.githubusercontent.com/42288570/118087111-56231100-b3c5-11eb-8fab-e96fb368a49f.mp4

**Comment by philippjfr** [comment]
Tests are failing:

https://github.com/holoviz/panel/pull/2303/checks?check_run_id=2572708149#step:12:1230

The problem is that `param.Color` only accepts hex colors right now. I really think it should accept valid HTML colors though.

**Comment by MarcSkovMadsen** [comment]
I will take a look @philippjfr . 

Please note the fast js only accepts hex or rgb. It does not accept html colors. And I need to use that to specify the color palette to use.

**Comment by philippjfr** [comment]
>I have just been used to them always failing to reasons outside my PR

We have a very different experience then, they have been working pretty consistently from my perspective.

**Comment by MarcSkovMadsen** [comment]
Maybe some of the approaches athttps://stackoverflow.com/questions/1573053/javascript-function-to-convert-color-names-to-hex-codes could be used to convert color name to hex or rgb on js side.

**Comment by mattpap** [comment]
> (...) could be used to convert color name to hex or rgb on js side.

bokehjs has color management utilities in `core/util/color`, which may be useful here.

**Comment by MarcSkovMadsen** [comment]
How would I use that in plain js in a `script` tag inside the `.html` template @mattpap ?

**Comment by MarcSkovMadsen** [comment]
You can now use named colors. For the Fast templates. So now things should work.

When working on the next PR (config widget to change style on the fly) some refactoring might have to be introduced. But that is to be determined.

**Comment by MarcSkovMadsen** [comment]
I don't plan to do more for now. I don't know of anything that needs improvement @philippjfr . When you have time please review and let me know. Thanks.

**Comment by philippjfr** [comment]
Sorry I let this sit for so long. All the changes look good but there appear to be a bunch of merge conflicts.

**Comment by MarcSkovMadsen** [comment]
Merge conflicts solved @philippjfr . I have tested that it still works manually and visually also.

**Pull request merged**
