### PR TITLE
Overhaul documentation

### PR DESCRIPTION
**Pull request by philippjfr**
- Redesign of homepage
- Redesign of Getting Started guide
- Leverage myst-parser Markdown more heavily
- Use [sphinx-design](https://sphinx-design.readthedocs.io/en/pydata-theme/index.html) for more modern look

Test build now available at: https://pyviz-dev.github.io/panel/

### CODE REVIEW

**Comment by philippjfr** [comment]
Copying comment from @MarcSkovMadsen in #3573:

https://pyviz-dev.github.io/panel/getting_started/core_concepts.html

1. Add autoreload

image

2. Include the Panel Jupyter Preview icon in the Tip

image

(New users will not know which icon you are talking about)

3. Remove "construct construct"

image

**Comment by MarcSkovMadsen** [comment]
Regarding ugly. The default HoloViews colors could be improved a lot. Especially the light blue for tooltips is soo badly looking.

image

**Comment by MarcSkovMadsen** [comment]
Exactly. Ubuntu is not available on windows.

**Comment by jbednar** [comment]
> Please focus on one api (probably pn.bind or pn.depends).

Definitely pn.bind, not pn.depends. PRs welcome to update any example using pn.depends to use pn.bind. Volunteers also welcome to propose a new default Bokeh theme. Now's a good time to do that, with Bokeh 3.0 coming up.

**Comment by MarcSkovMadsen** [comment]
Does HoloViz, anaconda or anyone around Bokeh have access to a designer. It would mean so much for Bokeh and HoloViz if Bokeh could get an attractive, modern Styling.

**Comment by jbednar** [comment]
Donation of design services would be greatly appreciated!

**Comment by maximlt** [comment]
Yes I'd love some help from a designer, and I'd be happy to see Orsted as a logo on Panel's site 🙃

**Comment by philippjfr** [comment]
Merging this as a first cut. Many follow up PRs to come.

**Pull request merged**
