### PR TITLE
Update Panelite and Discord links

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Panelite and Discord are not very visible. But legacy Gitter is 😄 

I try to improve the situation.

Closes https://github.com/holoviz/panel/issues/4642

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
Please note the discord badge will look like

image

Until someone like @philippjfr or @sophiamyang enables the *server widget* in our discord channel

image

The it will look like

image

**Comment by MarcSkovMadsen** [comment]
I've contributed a similar PR for HoloViz here https://github.com/holoviz/holoviz/pull/360/files that you (@philippjfr) might take a look at to 😄

**Comment by MarcSkovMadsen** [comment]
@droumis turned on the web widget. And it works

image

**Review by philippjfr — APPROVED** [review]
Thanks!

**Pull request merged**
