### PR TITLE
Perspective-Viewer WebComponent Example

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
A Perspective Viewer Web Component Example

Builds on to of the PR https://github.com/holoviz/panel/pull/1252

For now the example works on the server but not in the notebook.

#### Server

image

#### Notebook

image

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
I've created this support request with https://github.com/finos/perspective/issues/1016. I will need their help to get the `perspective-viewer` to register as a web component in a notebook.

**Comment by MarcSkovMadsen** [comment]
Improved significantly

- Got it working in Notebook
- Refactored into new Example Template
- Created nice looking app example

FYI. @philippjfr . I've refactored into the new template structure you suggested. Please take a look and let me know if things should change. Thanks.

perspective_viewer

**Comment by MarcSkovMadsen** [comment]
I need to do some more testing. I belive there are a few bugs.

**Comment by MarcSkovMadsen** [comment]
I have finished what I need to do. Waiting for review.

**Comment by philippjfr** [comment]
Closing for now as we discussed. Hope we can re-add it in some form later.

**Pull request closed without merging**
