### PR TITLE
Add Vue.js Custom Component Example

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Add a Vue.js Custom PDB Input Component as requested in https://github.com/holoviz/panel/issues/2948 and inspired by https://blog.reverielabs.com/python-vue-components/.

- [x] - Fix issue with having to import vue.js in `pn.config.js_files` in notebook if possible.

VuePdbInput

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
@philippjfr . Do you know why adding why to the `ReactiveHTML` `__javascript__` list is not enough in the notebook? It's enough on a web server.

**Comment by MarcSkovMadsen** [comment]
Here is how it works in Jupyter labs

https://user-images.githubusercontent.com/42288570/143542249-9ab6b38c-9807-4a49-a787-9395407aeb8b.mp4

**Comment by MarcSkovMadsen** [comment]
If someone has a better Vue.js example for Panel I would be willing to add a second Vue.js that adds functionality that is not already available in Panel.

**Comment by philippjfr** [comment]
Sat around a little while, sorry. Cleaned it up a bit.

**Review by philippjfr — APPROVED** [review]
Thanks and sorry for the delay!

**Pull request merged**
