### PR TITLE
Add DateRangePicker widget

### PR DESCRIPTION
**Pull request by TheoMathurin**
Replaces https://github.com/holoviz/panel/pull/2804
Closes https://github.com/holoviz/panel/issues/5844 and maybe https://github.com/holoviz/panel/issues/3789

As far as I know this reuse of Bokeh's implementation works fine.

As it's my first widget addition I'm open to suggestions to get closer to existing practices.

A small code to try it:

```python
import datetime as dt
import panel as pn
import panel.widgets as pnw


def display_value(event):
    col.append(date_range_picker.value)


def set_value(event):
    date_range_picker.value = (dt.date(2019, 1, 2), dt.date(2019, 1, 5))


def set_start_end(event):
    date_range_picker.start = dt.date(2020, 1, 2)
    date_range_picker.end = dt.date(2020, 2, 5)


date_range_picker = pnw.DateRangePicker(name='Date Range Picker', start=dt.date(2019, 1, 1), end=dt.date(2019, 1, 10))
button1 = pnw.Button(name='Display Value', on_click=display_value)
button2 = pnw.Button(name='Set Value', on_click=set_value)
button3 = pnw.Button(name='Set start end', on_click=set_start_end)

row = pn.Row(date_range_picker, pn.Column(button1, button2, button3))
col = pn.Column(row)

col.servable()
```

### CODE REVIEW

**Review by philippjfr — APPROVED** [review]
Looks great!

**Comment by fmfreeze** [comment]
@philippjfr may I ask, when this Daterangepicker is available in an official release?

And does it also support single date picking (start_date = end_date)? This is currently not supported by `pn.widgets.DatetimeRangePicker` when disabling time functionality.

**Comment by philippjfr** [comment]
Tagging 1.4.0rc1 on Monday so hopefully over the course of next week.

**Comment by philippjfr** [comment]
On the second part I'd have to check, you could try it out with 1.4.0b2 today.

**Comment by fmfreeze** [comment]
On monday i will try with 1.4rc2, thank you!

**Comment by TheoMathurin** [comment]
Same day selection is supported.

**Pull request merged**
