### PR TITLE
Improve Ipywidgets reference guide

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Working on https://github.com/developmentseed/lonboard/pull/539 and reading the questions in https://github.com/developmentseed/lonboard/issues/262 I released that the Ipywidgets reference guide does not explain fully how Panel supports ipywidgets.

This PR adds the missing explanations.

I've also found inspiration in the Shiny docs https://shiny.posit.co/py/docs/jupyter-widgets.html. Thanks to Shiny.

### CODE REVIEW

**Comment by philippjfr** [comment]
>If you want to convert your `ipywidget` to a Panel native widget, you can do so with Panel's [`AnyWidgetComponent`](../AnyWidgetComponent.ipynb), [`JSComponent`](../JSComponent.ipynb), or [`ReactComponent`](../ReactComponent.ipynb).

These links won't be correct, should be `../custom_components/...`.

**Comment by MarcSkovMadsen** [comment]
> > If you want to convert your `ipywidget` to a Panel native widget, you can do so with Panel's [`AnyWidgetComponent`](../AnyWidgetComponent.ipynb), [`JSComponent`](../JSComponent.ipynb), or [`ReactComponent`](../ReactComponent.ipynb).
> 
> These links won't be correct, should be `../custom_components/...`.

Thanks. Fixed.

**Comment by MarcSkovMadsen** [comment]
I changed the `Sizing` section to recommend fixing issues by settings `widget.layout.width=widget.layout.height="100%"`. At least that works for ipyleaflet and lonboard.

**Comment by MarcSkovMadsen** [comment]
Super seeded by #6912

**Pull request closed without merging**
