### PR TITLE
Binder fixes

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes https://github.com/holoviz/panel/issues/1500

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
So nice. Great work. 

Can I test this somewhere?

**Comment by MarcSkovMadsen** [comment]
Should there be a direct link to the App page as well?

**Comment by philippjfr** [comment]
>Can I test this somewhere?

Tagging an RC release after this is merged.

>Should there be a direct link to the App page as well?

Yes probably

**Comment by philippjfr** [comment]
Merging as is for now.

**Pull request merged**
