### PR TITLE
master to main

### PR DESCRIPTION
**Pull request by maximlt**

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
I like this one. How do we handle existing PRs into master?

**Comment by maximlt** [comment]
You shouldn't have anything to do for your PRs, they're automatically pointed to `main` by GitHub. On the repo main page GitHub should give you some indications on how to handle `main` on your local repo, basically suggesting to run:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by philippjfr** [comment]
Thanks @maximlt!

**Review by philippjfr — APPROVED** [review]
LGTM

**Pull request merged**
